INCLUDE "data/trainers/party_pointers.asm"

Trainers:
; Trainer data structure:
; - db "NAME@", TRAINERTYPE_* constant
; - 1 to 6 Pokémon:
;    * for TRAINERTYPE_NORMAL:     db level, species
;    * for TRAINERTYPE_MOVES:      db level, species, 4 moves
;    * for TRAINERTYPE_ITEM:       db level, species, item
;    * for TRAINERTYPE_ITEM_MOVES: db level, species, item, 4 moves
; - db -1 ; end

FalknerGroup:
	; FALKNER (1)
	db "FALKNER@", TRAINERTYPE_MOVES
	db  7, PIDGEY,     TACKLE, MUD_SLAP, NO_MOVE, NO_MOVE
	db  10, PIDGEOTTO,  TACKLE, MUD_SLAP, GUST, NO_MOVE
	db -1 ; end

WhitneyGroup:
	; WHITNEY (1)
	db "WHITNEY@", TRAINERTYPE_MOVES
	db 20, CLEFAIRY,   DOUBLESLAP, MIMIC, ENCORE, METRONOME
	db 22, MILTANK,    ROLLOUT, ATTRACT, STOMP, MILK_DRINK
	db -1 ; end

BugsyGroup:
	; BUGSY (1)
	db "BUGSY@", TRAINERTYPE_MOVES
	db 15, METAPOD,    TACKLE, STRING_SHOT, HARDEN, NO_MOVE
	db 15, KAKUNA,     POISON_STING, STRING_SHOT, HARDEN, NO_MOVE
	db 18, SCYTHER,    QUICK_ATTACK, LEER, FURY_CUTTER, NO_MOVE
	db -1 ; end

MortyGroup:
	; MORTY (1)
	db "MORTY@", TRAINERTYPE_MOVES
	db 23, GASTLY,     LICK, SPITE, MEAN_LOOK, CURSE
	db 23, HAUNTER,    HYPNOSIS, MIMIC, CURSE, NIGHT_SHADE
	db 28, GENGAR,     HYPNOSIS, SHADOW_BALL, MEAN_LOOK, DREAM_EATER
	db 25, HAUNTER,    SPITE, MEAN_LOOK, MIMIC, NIGHT_SHADE
	db -1 ; end

PryceGroup:
	; PRYCE (1)
	db "PRYCE@", TRAINERTYPE_MOVES
	db 30, SEEL,       HEADBUTT, ICY_WIND, AURORA_BEAM, REST
	db 32, DEWGONG,    HEADBUTT, ICY_WIND, AURORA_BEAM, REST
	db 34, PILOSWINE,  ICY_WIND, FURY_ATTACK, MIST, BLIZZARD
	db -1 ; end

JasmineGroup:
	; JASMINE (1)
	db "JASMINE@", TRAINERTYPE_MOVES
	db 33, MAGNEMITE,  THUNDERBOLT, SUPERSONIC, SONICBOOM, THUNDER_WAVE
	db 33, MAGNEMITE,  THUNDERBOLT, SUPERSONIC, SONICBOOM, THUNDER_WAVE
	db 39, STEELIX,    SCREECH, SUNNY_DAY, ROCK_THROW, IRON_TAIL
	db -1 ; end

ChuckGroup:
	; CHUCK (1)
	db "CHUCK@", TRAINERTYPE_MOVES
	db 30, PRIMEAPE,   LEER, RAGE, KARATE_CHOP, FURY_SWIPES
	db 33, POLIWRATH,  HYPNOSIS, MIND_READER, SURF, DYNAMICPUNCH
	db -1 ; end

ClairGroup:
	; CLAIR (1)
	db "CLAIR@", TRAINERTYPE_MOVES
	db 41, DRAGONAIR,  THUNDER_WAVE, SURF, SLAM, DRAGONBREATH
	db 41, DRAGONAIR,  THUNDER_WAVE, THUNDERBOLT, SLAM, DRAGONBREATH
	db 41, DRAGONAIR,  THUNDER_WAVE, ICE_BEAM, SLAM, DRAGONBREATH
	db 45, KINGDRA,    SMOKESCREEN, SURF, HYPER_BEAM, DRAGONBREATH
	db -1 ; end

Rival1Group:
	; RIVAL1 (1)
	db "?@", TRAINERTYPE_NORMAL
	db  5, CHIKORITA
	db -1 ; end

	; RIVAL1 (2)
	db "?@", TRAINERTYPE_NORMAL
	db  5, CYNDAQUIL
	db -1 ; end

	; RIVAL1 (3)
	db "?@", TRAINERTYPE_NORMAL
	db  5, TOTODILE
	db -1 ; end

	; RIVAL1 (4)
	db "?@", TRAINERTYPE_NORMAL
	db 13, GASTLY
	db 15, ZUBAT
	db 18, BAYLEEF
	db -1 ; end

	; RIVAL1 (5)
	db "?@", TRAINERTYPE_NORMAL
	db 13, GASTLY
	db 15, ZUBAT
	db 18, QUILAVA
	db -1 ; end

	; RIVAL1 (6)
	db "?@", TRAINERTYPE_NORMAL
	db 13, GASTLY
	db 15, ZUBAT
	db 18, CROCONAW
	db -1 ; end

	; RIVAL1 (7)
	db "?@", TRAINERTYPE_MOVES
	db 22, HAUNTER,    LICK, SPITE, MEAN_LOOK, CURSE
	db 20, MAGNEMITE,  TACKLE, THUNDERSHOCK, SUPERSONIC, SONICBOOM
	db 22, ZUBAT,      LEECH_LIFE, SUPERSONIC, BITE, CONFUSE_RAY
	db 24, BAYLEEF,    GROWL, REFLECT, RAZOR_LEAF, POISONPOWDER
	db -1 ; end

	; RIVAL1 (8)
	db "?@", TRAINERTYPE_MOVES
	db 22, HAUNTER,    LICK, SPITE, MEAN_LOOK, CURSE
	db 20, MAGNEMITE,  TACKLE, THUNDERSHOCK, SUPERSONIC, SONICBOOM
	db 22, ZUBAT,      LEECH_LIFE, SUPERSONIC, BITE, CONFUSE_RAY
	db 24, QUILAVA,    LEER, SMOKESCREEN, EMBER, QUICK_ATTACK
	db -1 ; end

	; RIVAL1 (9)
	db "?@", TRAINERTYPE_MOVES
	db 22, HAUNTER,    LICK, SPITE, MEAN_LOOK, CURSE
	db 20, MAGNEMITE,  TACKLE, THUNDERSHOCK, SUPERSONIC, SONICBOOM
	db 22, ZUBAT,      LEECH_LIFE, SUPERSONIC, BITE, CONFUSE_RAY
	db 24, CROCONAW,   LEER, RAGE, WATER_GUN, BITE
	db -1 ; end

	; RIVAL1 (10)
	db "?@", TRAINERTYPE_MOVES
	db 33, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 31, MAGNEMITE,  TACKLE, THUNDERSHOCK, SONICBOOM, THUNDER_WAVE
	db 33, HAUNTER,    LICK, MEAN_LOOK, CURSE, SHADOW_BALL
	db 36, SNEASEL,    LEER, QUICK_ATTACK, SCREECH, FAINT_ATTACK
	db 36, MEGANIUM,   REFLECT, RAZOR_LEAF, POISONPOWDER, BODY_SLAM
	db -1 ; end

	; RIVAL1 (11)
	db "?@", TRAINERTYPE_MOVES
	db 33, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 31, MAGNEMITE,  TACKLE, THUNDERSHOCK, SONICBOOM, THUNDER_WAVE
	db 33, HAUNTER,    LICK, MEAN_LOOK, CURSE, SHADOW_BALL
	db 36, SNEASEL,    LEER, QUICK_ATTACK, SCREECH, FAINT_ATTACK
	db 36, QUILAVA,    SMOKESCREEN, EMBER, QUICK_ATTACK, FLAME_WHEEL
	db -1 ; end

	; RIVAL1 (12)
	db "?@", TRAINERTYPE_MOVES
	db 33, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 31, MAGNEMITE,  TACKLE, THUNDERSHOCK, SONICBOOM, THUNDER_WAVE
	db 33, HAUNTER,    LICK, MEAN_LOOK, CURSE, SHADOW_BALL
	db 36, SNEASEL,    LEER, QUICK_ATTACK, SCREECH, FAINT_ATTACK
	db 36, FERALIGATR, RAGE, WATER_GUN, BITE, SCARY_FACE
	db -1 ; end

	; RIVAL1 (13)
	db "?@", TRAINERTYPE_MOVES
	db 38, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 40, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 39, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 39, HAUNTER,    MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 39, KADABRA,    DISABLE, PSYBEAM, RECOVER, FUTURE_SIGHT
	db 42, MEGANIUM,   REFLECT, RAZOR_LEAF, POISONPOWDER, BODY_SLAM
	db -1 ; end

	; RIVAL1 (14)
	db "?@", TRAINERTYPE_MOVES
	db 38, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 40, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 39, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 39, HAUNTER,    MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 39, KADABRA,    DISABLE, PSYBEAM, RECOVER, FUTURE_SIGHT
	db 42, TYPHLOSION, SMOKESCREEN, EMBER, QUICK_ATTACK, FLAME_WHEEL
	db -1 ; end

	; RIVAL1 (15)
	db "?@", TRAINERTYPE_MOVES
	db 38, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 40, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 38, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 39, HAUNTER,    MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 39, KADABRA,    DISABLE, PSYBEAM, RECOVER, FUTURE_SIGHT
	db 42, FERALIGATR, RAGE, WATER_GUN, SCARY_FACE, SLASH
	db -1 ; end

PokemonProfGroup:

WillGroup:
	; WILL (1)
	db "WILL@", TRAINERTYPE_MOVES
	db 45, XATU,       QUICK_ATTACK, FUTURE_SIGHT, CONFUSE_RAY, PSYCHIC_M
	db 46, JYNX,       DOUBLESLAP, LOVELY_KISS, ICE_PUNCH, PSYCHIC_M
	db 46, EXEGGUTOR,  REFLECT, LEECH_SEED, EGG_BOMB, PSYCHIC_M
	db 46, SLOWBRO,    CURSE, AMNESIA, BODY_SLAM, PSYCHIC_M
	db 47, XATU,       QUICK_ATTACK, FUTURE_SIGHT, CONFUSE_RAY, PSYCHIC_M
	db -1 ; end

PKMNTrainerGroup:
	; CAL (1)
	db "CAL@", TRAINERTYPE_NORMAL
	db 11, CHIKORITA
	db 11, CYNDAQUIL
	db 11, TOTODILE
	db -1 ; end

	; CAL (2)
	db "CAL@", TRAINERTYPE_NORMAL
	db 33, BAYLEEF
	db 33, QUILAVA
	db 33, CROCONAW
	db -1 ; end

	; CAL (3)
	db "CAL@", TRAINERTYPE_NORMAL
	db 56, MEGANIUM
	db 56, TYPHLOSION
	db 56, FERALIGATR
	db -1 ; end

BrunoGroup:
	; BRUNO (1)
	db "BRUNO@", TRAINERTYPE_MOVES
	db 47, HITMONTOP,  PURSUIT, QUICK_ATTACK, DIG, DETECT
	db 47, HITMONLEE,  SWAGGER, DOUBLE_KICK, HI_JUMP_KICK, FORESIGHT
	db 47, HITMONCHAN, THUNDERPUNCH, ICE_PUNCH, FIRE_PUNCH, MACH_PUNCH
	db 48, ONIX,       BIND, EARTHQUAKE, SANDSTORM, ROCK_SLIDE
	db 51, MACHAMP,    ROCK_SLIDE, FORESIGHT, VITAL_THROW, CROSS_CHOP
	db -1 ; end

KarenGroup:
	; KAREN (1)
	db "KAREN@", TRAINERTYPE_MOVES
	db 47, UMBREON,    SAND_ATTACK, CONFUSE_RAY, FAINT_ATTACK, MEAN_LOOK
	db 47, VILEPLUME,  STUN_SPORE, ACID, MOONLIGHT, PETAL_DANCE
	db 50, GENGAR,     LICK, SPITE, CURSE, DESTINY_BOND
	db 49, MURKROW,    QUICK_ATTACK, WHIRLWIND, PURSUIT, FAINT_ATTACK
	db 52, HOUNDOOM,   ROAR, PURSUIT, FLAMETHROWER, CRUNCH
	db -1 ; end

KogaGroup:
	; KOGA (1)
	db "KOGA@", TRAINERTYPE_MOVES
	db 45, ARIADOS,    DOUBLE_TEAM, SPIDER_WEB, BATON_PASS, GIGA_DRAIN
	db 46, VENOMOTH,   SUPERSONIC, GUST, PSYCHIC_M, TOXIC
	db 48, FORRETRESS, PROTECT, SWIFT, EXPLOSION, SPIKES
	db 47, MUK,        MINIMIZE, ACID_ARMOR, SLUDGE_BOMB, TOXIC
	db 49, CROBAT,     DOUBLE_TEAM, QUICK_ATTACK, WING_ATTACK, TOXIC
	db -1 ; end

ChampionGroup:
	; CHAMPION (1)
	db "LANCE@", TRAINERTYPE_MOVES
	db 49, GYARADOS,   FLAIL, RAIN_DANCE, SURF, HYPER_BEAM
	db 52, DRAGONITE,  THUNDER_WAVE, TWISTER, THUNDER, HYPER_BEAM
	db 52, DRAGONITE,  THUNDER_WAVE, TWISTER, BLIZZARD, HYPER_BEAM
	db 51, AERODACTYL, WING_ATTACK, ANCIENTPOWER, ROCK_SLIDE, HYPER_BEAM
	db 51, CHARIZARD,  FLAMETHROWER, WING_ATTACK, SLASH, HYPER_BEAM
	db 56, DRAGONITE,  FIRE_BLAST, SAFEGUARD, OUTRAGE, HYPER_BEAM
	db -1 ; end

BrockGroup:
	; BROCK (1)
	db "BROCK@", TRAINERTYPE_MOVES
	db 46, GRAVELER,   DEFENSE_CURL, ROCK_SLIDE, ROLLOUT, EARTHQUAKE
	db 46, RHYHORN,    FURY_ATTACK, SCARY_FACE, EARTHQUAKE, HORN_DRILL
	db 47, OMASTAR,    BITE, SURF, PROTECT, SPIKE_CANNON
	db 49, ONIX,       BIND, ROCK_SLIDE, BIDE, SANDSTORM
	db 47, KABUTOPS,   SLASH, SURF, ENDURE, GIGA_DRAIN
	db -1 ; end

MistyGroup:
	; MISTY (1)
	db "MISTY@", TRAINERTYPE_MOVES
	db 47, GOLDUCK,    SURF, DISABLE, PSYCH_UP, PSYCHIC_M
	db 47, QUAGSIRE,   SURF, AMNESIA, EARTHQUAKE, RAIN_DANCE
	db 49, LAPRAS,     SURF, PERISH_SONG, BLIZZARD, RAIN_DANCE
	db 52, STARMIE,    SURF, CONFUSE_RAY, RECOVER, ICE_BEAM
	db -1 ; end

LtSurgeGroup:
	; LT_SURGE (1)
	db "LT.SURGE@", TRAINERTYPE_MOVES
	db 49, RAICHU,     THUNDER_WAVE, QUICK_ATTACK, THUNDERBOLT, THUNDER
	db 45, ELECTRODE,  SCREECH, DOUBLE_TEAM, SWIFT, EXPLOSION
	db 45, MAGNETON,   LOCK_ON, DOUBLE_TEAM, SWIFT, ZAP_CANNON
	db 45, ELECTRODE,  SCREECH, DOUBLE_TEAM, SWIFT, EXPLOSION
	db 51, ELECTABUZZ, QUICK_ATTACK, THUNDERPUNCH, LIGHT_SCREEN, THUNDER
	db -1 ; end

ScientistGroup:
	; SCIENTIST (1)
	db "ROSS@", TRAINERTYPE_NORMAL
	db 24, KOFFING
	db 24, KOFFING
	db -1 ; end

	; SCIENTIST (2)
	db "MITCH@", TRAINERTYPE_NORMAL
	db 27, DITTO
	db -1 ; end

	; SCIENTIST (3)
	db "JED@", TRAINERTYPE_NORMAL
	db 22, MAGNEMITE
	db 22, MAGNEMITE
	db 22, MAGNEMITE
	db -1 ; end

	; SCIENTIST (4)
	db "MARC@", TRAINERTYPE_NORMAL
	db 30, MAGNEMITE
	db 30, MAGNEMITE
	db 30, MAGNEMITE
	db -1 ; end

	; SCIENTIST (5)
	db "RICH@", TRAINERTYPE_MOVES
	db 33, PORYGON,    CONVERSION, CONVERSION33, RECOVER, TRI_ATTACK
	db -1 ; end

ErikaGroup:
	; ERIKA (1)
	db "ERIKA@", TRAINERTYPE_MOVES
	db 47, TANGELA,    VINE_WHIP, BIND, GIGA_DRAIN, SLEEP_POWDER
	db 46, JUMPLUFF,   MEGA_DRAIN, LEECH_SEED, COTTON_SPORE, GIGA_DRAIN
	db 51, VICTREEBEL, SUNNY_DAY, SYNTHESIS, ACID, RAZOR_LEAF
	db 51, BELLOSSOM,  SUNNY_DAY, SYNTHESIS, PETAL_DANCE, SOLARBEAM
	db -1 ; end

YoungsterGroup:
	; YOUNGSTER (1)
	db "JOEY@", TRAINERTYPE_NORMAL
	db  4, RATTATA
	db -1 ; end

	; YOUNGSTER (2)
	db "MIKEY@", TRAINERTYPE_NORMAL
	db  2, PIDGEY
	db  4, RATTATA
	db -1 ; end

	; YOUNGSTER (3)
	db "ALBERT@", TRAINERTYPE_NORMAL
	db  6, RATTATA
	db  9, ZUBAT
	db -1 ; end

	; YOUNGSTER (4)
	db "GORDON@", TRAINERTYPE_NORMAL
	db 11, WOOPER
	db -1 ; end

	; YOUNGSTER (5)
	db "SAMUEL@", TRAINERTYPE_NORMAL
	db  7, RATTATA
	db 11, SANDSHREW
	db  9, SPEAROW
	db  9, SPEAROW
	db -1 ; end

	; YOUNGSTER (6)
	db "IAN@", TRAINERTYPE_NORMAL
	db 11, MANKEY
	db 13, DIGLETT
	db -1 ; end

	; YOUNGSTER (7)
	db "JOEY@", TRAINERTYPE_NORMAL
	db 16, RATTATA
	db -1 ; end

	; YOUNGSTER (8)
	db "JOEY@", TRAINERTYPE_MOVES
	db 23, RATICATE,   TAIL_WHIP, QUICK_ATTACK, HYPER_FANG, SCARY_FACE
	db -1 ; end

	; YOUNGSTER (9)
	db "WARREN@", TRAINERTYPE_NORMAL
	db 39, FEAROW
	db -1 ; end

	; YOUNGSTER (10)
	db "JIMMY@", TRAINERTYPE_NORMAL
	db 37, RATICATE
	db 37, ARBOK
	db -1 ; end

	; YOUNGSTER (11)
	db "OWEN@", TRAINERTYPE_NORMAL
	db 39, GROWLITHE
	db -1 ; end

	; YOUNGSTER (12)
	db "JASON@", TRAINERTYPE_NORMAL
	db 37, SANDSLASH
	db 37, CROBAT
	db -1 ; end

SchoolboyGroup:
	; SCHOOLBOY (1)
	db "JACK@", TRAINERTYPE_NORMAL
	db 13, ODDISH
	db 16, VOLTORB
	db -1 ; end

	; SCHOOLBOY (2)
	db "KIPP@", TRAINERTYPE_NORMAL
	db 30, VOLTORB
	db 30, MAGNEMITE
	db 34, VOLTORB
	db 34, MAGNETON
	db -1 ; end

	; SCHOOLBOY (3)
	db "ALAN@", TRAINERTYPE_NORMAL
	db 18, TANGELA
	db -1 ; end

	; SCHOOLBOY (4)
	db "JOHNNY@", TRAINERTYPE_NORMAL
	db 32, BELLSPROUT
	db 34, WEEPINBELL
	db 37, VICTREEBEL
	db -1 ; end

	; SCHOOLBOY (5)
	db "DANNY@", TRAINERTYPE_NORMAL
	db 34, JYNX
	db 34, ELECTABUZZ
	db 34, MAGMAR
	db -1 ; end

	; SCHOOLBOY (6)
	db "TOMMY@", TRAINERTYPE_NORMAL
	db 36, XATU
	db 38, ALAKAZAM
	db -1 ; end

	; SCHOOLBOY (7)
	db "DUDLEY@", TRAINERTYPE_NORMAL
	db 39, ODDISH
	db -1 ; end

	; SCHOOLBOY (8)
	db "JOE@", TRAINERTYPE_NORMAL
	db 37, TANGELA
	db 37, VAPOREON
	db -1 ; end

	; SCHOOLBOY (9)
	db "BILLY@", TRAINERTYPE_NORMAL
	db 30, PARAS
	db 30, PARAS
	db 30, POLIWHIRL
	db 39, DITTO
	db -1 ; end

	; SCHOOLBOY (10)
	db "CHAD@", TRAINERTYPE_NORMAL
	db 21, MR__MIME
	db -1 ; end

	; SCHOOLBOY (11)
	db "NATE@", TRAINERTYPE_NORMAL
	db 36, LEDIAN
	db 36, EXEGGUTOR
	db -1 ; end

	; SCHOOLBOY (12)
	db "RICKY@", TRAINERTYPE_NORMAL
	db 36, AIPOM
	db 36, DITTO
	db -1 ; end

	; SCHOOLBOY (13)
	db "JACK@", TRAINERTYPE_NORMAL
	db 15, ODDISH
	db 19, VOLTORB
	db -1 ; end

	; SCHOOLBOY (14)
	db "JACK@", TRAINERTYPE_NORMAL
	db 31, GLOOM
	db 34, ELECTRODE
	db -1 ; end

	; SCHOOLBOY (15)
	db "ALAN@", TRAINERTYPE_NORMAL
	db 19, TANGELA
	db 19, YANMA
	db -1 ; end

	; SCHOOLBOY (16)
	db "ALAN@", TRAINERTYPE_NORMAL
	db 22, NATU
	db 24, TANGELA
	db 22, QUAGSIRE
	db 28, YANMA
	db -1 ; end

	; SCHOOLBOY (17)
	db "CHAD@", TRAINERTYPE_NORMAL
	db 21, MR__MIME
	db 21, MAGNEMITE
	db -1 ; end

	; SCHOOLBOY (18)
	db "CHAD@", TRAINERTYPE_NORMAL
	db 30, MR__MIME
	db 34, MAGNETON
	db -1 ; end

BirdKeeperGroup:
	; BIRD_KEEPER (1)
	db "ROD@", TRAINERTYPE_NORMAL
	db  7, PIDGEY
	db  7, PIDGEY
	db -1 ; end

	; BIRD_KEEPER (2)
	db "ABE@", TRAINERTYPE_NORMAL
	db  10, SPEAROW
	db -1 ; end

	; BIRD_KEEPER (3)
	db "BRYAN@", TRAINERTYPE_NORMAL
	db 13, PIDGEY
	db 15, PIDGEOTTO
	db -1 ; end

	; BIRD_KEEPER (4)
	db "THEO@", TRAINERTYPE_NORMAL
	db 19, PIDGEY
	db 16, PIDGEY
	db 21, PIDGEY
	db 16, PIDGEY
	db 16, PIDGEY
	db -1 ; end

	; BIRD_KEEPER (5)
	db "TOBY@", TRAINERTYPE_NORMAL
	db 16, DODUO
	db 18, DODUO
	db 19, DODUO
	db -1 ; end

	; BIRD_KEEPER (6)
	db "DENIS@", TRAINERTYPE_NORMAL
	db 20, SPEAROW
	db 22, FEAROW
	db 20, SPEAROW
	db -1 ; end

	; BIRD_KEEPER (7)
	db "VANCE@", TRAINERTYPE_NORMAL
	db 28, PIDGEOTTO
	db 28, PIDGEOTTO
	db -1 ; end

	; BIRD_KEEPER (8)
	db "HANK@", TRAINERTYPE_NORMAL
	db 13, PIDGEY
	db 38, PIDGEOT
	db -1 ; end

	; BIRD_KEEPER (9)
	db "ROY@", TRAINERTYPE_NORMAL
	db 32, FEAROW
	db 39, FEAROW
	db -1 ; end

	; BIRD_KEEPER (10)
	db "BORIS@", TRAINERTYPE_NORMAL
	db 33, DODUO
	db 31, DODUO
	db 36, DODRIO
	db -1 ; end

	; BIRD_KEEPER (11)
	db "BOB@", TRAINERTYPE_NORMAL
	db 38, NOCTOWL
	db -1 ; end

	; BIRD_KEEPER (12)
	db "JOSE@", TRAINERTYPE_NORMAL
	db 41, FARFETCH_D
	db -1 ; end

	; BIRD_KEEPER (13)
	db "PETER@", TRAINERTYPE_NORMAL
	db  6, PIDGEY
	db  6, PIDGEY
	db  9, SPEAROW
	db -1 ; end

	; BIRD_KEEPER (14)
	db "JOSE@", TRAINERTYPE_NORMAL
	db 39, FARFETCH_D
	db -1 ; end

	; BIRD_KEEPER (15)
	db "PERRY@", TRAINERTYPE_NORMAL
	db 38, FARFETCH_D
	db -1 ; end

	; BIRD_KEEPER (16)
	db "BRET@", TRAINERTYPE_NORMAL
	db 36, PIDGEOTTO
	db 36, FEAROW
	db -1 ; end

	; BIRD_KEEPER (17)
	db "JOSE@", TRAINERTYPE_NORMAL
	db 46, FARFETCH_D
	db -1 ; end

	; BIRD_KEEPER (18)
	db "VANCE@", TRAINERTYPE_NORMAL
	db 34, PIDGEOTTO
	db 37, PIDGEOTTO
	db -1 ; end

	; BIRD_KEEPER (19)
	db "VANCE@", TRAINERTYPE_NORMAL
	db 39, PIDGEOTTO
	db 41, PIDGEOT
	db -1 ; end

LassGroup:
	; LASS (1)
	db "CARRIE@", TRAINERTYPE_MOVES
	db 20, SNUBBULL,   SCARY_FACE, CHARM, BITE, LICK
	db -1 ; end

	; LASS (2)
	db "BRIDGET@", TRAINERTYPE_NORMAL
	db 16, JIGGLYPUFF
	db 16, JIGGLYPUFF
	db 16, JIGGLYPUFF
	db -1 ; end

	; LASS (3)
	db "ALICE@", TRAINERTYPE_NORMAL
	db 33, GLOOM
	db 38, ARBOK
	db 33, GLOOM
	db -1 ; end

	; LASS (4)
	db "KRISE@", TRAINERTYPE_NORMAL
	db 13, ODDISH
	db 16, CUBONE
	db -1 ; end

	; LASS (5)
	db "CONNIE@", TRAINERTYPE_NORMAL
	db 23, MARILL
	db -1 ; end

	; LASS (6)
	db "LINDA@", TRAINERTYPE_NORMAL
	db 33, BULBASAUR
	db 36, IVYSAUR
	db 38, VENUSAUR
	db -1 ; end

	; LASS (7)
	db "LAURA@", TRAINERTYPE_NORMAL
	db 31, GLOOM
	db 34, PIDGEOTTO
	db 34, BELLOSSOM
	db -1 ; end

	; LASS (8)
	db "SHANNON@", TRAINERTYPE_NORMAL
	db 32, PARAS
	db 32, PARAS
	db 36, PARASECT
	db -1 ; end

	; LASS (9)
	db "MICHELLE@", TRAINERTYPE_NORMAL
	db 36, SKIPLOOM
	db 37, HOPPIP
	db 38, JUMPLUFF
	db -1 ; end

	; LASS (10)
	db "DANA@", TRAINERTYPE_MOVES
	db 20, FLAAFFY,    TACKLE, GROWL, THUNDERSHOCK, THUNDER_WAVE
	db 20, PSYDUCK,    SCRATCH, TAIL_WHIP, DISABLE, CONFUSION
	db -1 ; end

	; LASS (11)
	db "ELLEN@", TRAINERTYPE_NORMAL
	db 33, WIGGLYTUFF
	db 38, GRANBULL
	db -1 ; end

	; LASS (12)
	db "CONNIE@", TRAINERTYPE_NORMAL
	db 23, MARILL
	db -1 ; end

	; LASS (13)
	db "CONNIE@", TRAINERTYPE_NORMAL
	db 23, MARILL
	db -1 ; end

	; LASS (14)
	db "DANA@", TRAINERTYPE_MOVES
	db 23, FLAAFFY,    TACKLE, GROWL, THUNDERSHOCK, THUNDER_WAVE
	db 23, PSYDUCK,    SCRATCH, TAIL_WHIP, DISABLE, CONFUSION
	db -1 ; end

	; LASS (15)
	db "DANA@", TRAINERTYPE_MOVES
	db 32, PSYDUCK,    SCRATCH, DISABLE, CONFUSION, SCREECH
	db 32, AMPHAROS,   TACKLE, THUNDERSHOCK, THUNDER_WAVE, COTTON_SPORE
	db -1 ; end

JanineGroup:
	; JANINE (1)
	db "JANINE@", TRAINERTYPE_MOVES
	db 40, CROBAT,     SCREECH, SUPERSONIC, CONFUSE_RAY, WING_ATTACK
	db 40, WEEZING,    SMOG, SLUDGE_BOMB, TOXIC, EXPLOSION
	db 40, WEEZING,    SMOG, SLUDGE_BOMB, TOXIC, EXPLOSION
	db 37, ARIADOS,    SCARY_FACE, GIGA_DRAIN, STRING_SHOT, NIGHT_SHADE
	db 43, VENOMOTH,   FORESIGHT, DOUBLE_TEAM, GUST, PSYCHIC_M
	db -1 ; end

CooltrainerMGroup:
	; COOLTRAINERM (1)
	db "NICK@", TRAINERTYPE_MOVES
	db 29, CHARMANDER, EMBER, SMOKESCREEN, RAGE, SCARY_FACE
	db 29, SQUIRTLE,   WITHDRAW, WATER_GUN, BITE, CURSE
	db 29, BULBASAUR,  LEECH_SEED, POISONPOWDER, SLEEP_POWDER, RAZOR_LEAF
	db -1 ; end

	; COOLTRAINERM (2)
	db "AARON@", TRAINERTYPE_NORMAL
	db 27, IVYSAUR
	db 27, CHARMELEON
	db 27, WARTORTLE
	db -1 ; end

	; COOLTRAINERM (3)
	db "PAUL@", TRAINERTYPE_NORMAL
	db 38, DRATINI
	db 38, DRATINI
	db 38, DRATINI
	db -1 ; end

	; COOLTRAINERM (4)
	db "CODY@", TRAINERTYPE_NORMAL
	db 38, HORSEA
	db 40, SEADRA
	db -1 ; end

	; COOLTRAINERM (5)
	db "MIKE@", TRAINERTYPE_NORMAL
	db 41, DRAGONAIR
	db -1 ; end

	; COOLTRAINERM (6)
	db "GAVEN@", TRAINERTYPE_MOVES
	db 38, VICTREEBEL, WRAP, TOXIC, ACID, RAZOR_LEAF
	db 38, KINGLER,    BUBBLEBEAM, STOMP, GUILLOTINE, PROTECT
	db 38, FLAREON,    SAND_ATTACK, QUICK_ATTACK, BITE, FIRE_SPIN
	db -1 ; end

	; COOLTRAINERM (7)
	db "GAVEN@", TRAINERTYPE_MOVES
	db 42, VICTREEBEL, WRAP, TOXIC, ACID, RAZOR_LEAF
	db 42, KINGLER,    BUBBLEBEAM, STOMP, GUILLOTINE, PROTECT
	db 42, FLAREON,    SAND_ATTACK, QUICK_ATTACK, BITE, FIRE_SPIN
	db -1 ; end

	; COOLTRAINERM (8)
	db "RYAN@", TRAINERTYPE_MOVES
	db 28, PIDGEOT,    SAND_ATTACK, QUICK_ATTACK, WHIRLWIND, WING_ATTACK
	db 30, ELECTABUZZ, THUNDERPUNCH, LIGHT_SCREEN, SWIFT, SCREECH
	db -1 ; end

	; COOLTRAINERM (9)
	db "JAKE@", TRAINERTYPE_MOVES
	db 37, PARASECT,   LEECH_LIFE, SPORE, SLASH, SWORDS_DANCE
	db 39, GOLDUCK,    CONFUSION, SCREECH, PSYCH_UP, FURY_SWIPES
	db -1 ; end

	; COOLTRAINERM (10)
	db "GAVEN@", TRAINERTYPE_MOVES
	db 36, VICTREEBEL, WRAP, TOXIC, ACID, RAZOR_LEAF
	db 36, KINGLER,    BUBBLEBEAM, STOMP, GUILLOTINE, PROTECT
	db 36, FLAREON,    SAND_ATTACK, QUICK_ATTACK, BITE, FIRE_SPIN
	db -1 ; end

	; COOLTRAINERM (11)
	db "BLAKE@", TRAINERTYPE_MOVES
	db 37, MAGNETON,   THUNDERBOLT, SUPERSONIC, SWIFT, SCREECH
	db 34, QUAGSIRE,   WATER_GUN, SLAM, AMNESIA, EARTHQUAKE
	db 34, EXEGGCUTE,  LEECH_SEED, CONFUSION, SLEEP_POWDER, SOLARBEAM
	db -1 ; end

	; COOLTRAINERM (12)
	db "BRIAN@", TRAINERTYPE_MOVES
	db 39, SANDSLASH,  SAND_ATTACK, POISON_STING, SLASH, SWIFT
	db -1 ; end

	; COOLTRAINERM (13)
	db "ERICK@", TRAINERTYPE_NORMAL
	db 11, BULBASAUR
	db 11, CHARMANDER
	db 11, SQUIRTLE
	db -1 ; end

	; COOLTRAINERM (14)
	db "ANDY@", TRAINERTYPE_NORMAL
	db 11, BULBASAUR
	db 11, CHARMANDER
	db 11, SQUIRTLE
	db -1 ; end

	; COOLTRAINERM (15)
	db "TYLER@", TRAINERTYPE_NORMAL
	db 11, BULBASAUR
	db 11, CHARMANDER
	db 11, SQUIRTLE
	db -1 ; end

	; COOLTRAINERM (16)
	db "SEAN@", TRAINERTYPE_NORMAL
	db 39, FLAREON
	db 39, TANGELA
	db 39, TAUROS
	db -1 ; end

	; COOLTRAINERM (17)
	db "KEVIN@", TRAINERTYPE_NORMAL
	db 42, RHYHORN
	db 39, CHARMELEON
	db 39, WARTORTLE
	db -1 ; end

	; COOLTRAINERM (18)
	db "STEVE@", TRAINERTYPE_NORMAL
	db 15, BULBASAUR
	db 15, CHARMANDER
	db 15, SQUIRTLE
	db -1 ; end

	; COOLTRAINERM (19)
	db "ALLEN@", TRAINERTYPE_MOVES
	db 30, CHARMELEON, EMBER, SMOKESCREEN, RAGE, SCARY_FACE
	db -1 ; end

CooltrainerFGroup:
	; COOLTRAINERF (1)
	db "GWEN@", TRAINERTYPE_NORMAL
	db 29, EEVEE
	db 24, FLAREON
	db 24, VAPOREON
	db 24, JOLTEON
	db -1 ; end

	; COOLTRAINERF (2)
	db "LOIS@", TRAINERTYPE_MOVES
	db 28, SKIPLOOM,   SYNTHESIS, POISONPOWDER, MEGA_DRAIN, LEECH_SEED
	db 28, NINETALES,  EMBER, QUICK_ATTACK, CONFUSE_RAY, SAFEGUARD
	db -1 ; end

	; COOLTRAINERF (3)
	db "FRAN@", TRAINERTYPE_NORMAL
	db 41, SEADRA
	db -1 ; end

	; COOLTRAINERF (4)
	db "LOLA@", TRAINERTYPE_NORMAL
	db 38, DRATINI
	db 40, DRAGONAIR
	db -1 ; end

	; COOLTRAINERF (5)
	db "KATE@", TRAINERTYPE_NORMAL
	db 29, SHELLDER
	db 31, CLOYSTER
	db -1 ; end

	; COOLTRAINERF (6)
	db "IRENE@", TRAINERTYPE_NORMAL
	db 24, GOLDEEN
	db 27, SEAKING
	db -1 ; end

	; COOLTRAINERF (7)
	db "KELLY@", TRAINERTYPE_NORMAL
	db 30, MARILL
	db 27, WARTORTLE
	db 27, WARTORTLE
	db -1 ; end

	; COOLTRAINERF (8)
	db "JOYCE@", TRAINERTYPE_MOVES
	db 40, PIKACHU,    QUICK_ATTACK, DOUBLE_TEAM, THUNDERBOLT, THUNDER
	db 36, BLASTOISE,  BITE, CURSE, SURF, RAIN_DANCE
	db -1 ; end

	; COOLTRAINERF (9)
	db "BETH@", TRAINERTYPE_MOVES
	db 40, RAPIDASH,   STOMP, FIRE_SPIN, FURY_ATTACK, AGILITY
	db -1 ; end

	; COOLTRAINERF (10)
	db "REENA@", TRAINERTYPE_NORMAL
	db 34, STARMIE
	db 37, NIDOQUEEN
	db 34, STARMIE
	db -1 ; end

	; COOLTRAINERF (11)
	db "MEGAN@", TRAINERTYPE_MOVES
	db 36, BULBASAUR,  GROWL, LEECH_SEED, POISONPOWDER, RAZOR_LEAF
	db 36, IVYSAUR,    GROWL, LEECH_SEED, POISONPOWDER, RAZOR_LEAF
	db 36, VENUSAUR,   BODY_SLAM, SLEEP_POWDER, RAZOR_LEAF, SWEET_SCENT
	db -1 ; end

	; COOLTRAINERF (12)
	db "BETH@", TRAINERTYPE_MOVES
	db 42, RAPIDASH,   STOMP, FIRE_SPIN, FURY_ATTACK, AGILITY
	db -1 ; end

	; COOLTRAINERF (13)
	db "CAROL@", TRAINERTYPE_NORMAL
	db 39, ELECTRODE
	db 39, STARMIE
	db 39, NINETALES
	db -1 ; end

	; COOLTRAINERF (14)
	db "QUINN@", TRAINERTYPE_NORMAL
	db 42, IVYSAUR
	db 42, STARMIE
	db -1 ; end

	; COOLTRAINERF (15)
	db "EMMA@", TRAINERTYPE_NORMAL
	db 31, POLIWHIRL
	db -1 ; end

	; COOLTRAINERF (16)
	db "CYBIL@", TRAINERTYPE_MOVES
	db 28, BUTTERFREE, CONFUSION, SLEEP_POWDER, WHIRLWIND, GUST
	db 28, BELLOSSOM,  ABSORB, STUN_SPORE, ACID, SOLARBEAM
	db -1 ; end

	; COOLTRAINERF (17)
	db "JENN@", TRAINERTYPE_NORMAL
	db 27, STARYU
	db 29, STARMIE
	db -1 ; end

	; COOLTRAINERF (18)
	db "BETH@", TRAINERTYPE_MOVES
	db 47, RAPIDASH,   STOMP, FIRE_SPIN, FURY_ATTACK, AGILITY
	db -1 ; end

	; COOLTRAINERF (19)
	db "REENA@", TRAINERTYPE_NORMAL
	db 37, STARMIE
	db 39, NIDOQUEEN
	db 37, STARMIE
	db -1 ; end

	; COOLTRAINERF (20)
	db "REENA@", TRAINERTYPE_NORMAL
	db 41, STARMIE
	db 43, NIDOQUEEN
	db 41, STARMIE
	db -1 ; end

BeautyGroup:
	; BEAUTY (1)
	db "VICTORIA@", TRAINERTYPE_NORMAL
	db  10, SENTRET
	db 14, SENTRET
	db 19, SENTRET
	db -1 ; end

	; BEAUTY (2)
	db "SAMANTHA@", TRAINERTYPE_MOVES
	db 18, MEOWTH,     SCRATCH, GROWL, BITE, PAY_DAY
	db 18, MEOWTH,     SCRATCH, GROWL, BITE, SLASH
	db -1 ; end

	; BEAUTY (3)
	db "JULIE@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (4)
	db "JACLYN@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (5)
	db "BRENDA@", TRAINERTYPE_NORMAL
	db 18, FURRET
	db -1 ; end

	; BEAUTY (6)
	db "CASSIE@", TRAINERTYPE_NORMAL
	db 31, VILEPLUME
	db 38, BUTTERFREE
	db -1 ; end

	; BEAUTY (7)
	db "CAROLINE@", TRAINERTYPE_NORMAL
	db 33, MARILL
	db 36, SEEL
	db 33, MARILL
	db -1 ; end

	; BEAUTY (8)
	db "CARLENE@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (9)
	db "JESSICA@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (10)
	db "RACHAEL@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (11)
	db "ANGELICA@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (12)
	db "KENDRA@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (13)
	db "VERONICA@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (14)
	db "JULIA@", TRAINERTYPE_NORMAL
	db 36, PARAS
	db 36, EXEGGCUTE
	db 39, PARASECT
	db -1 ; end

	; BEAUTY (15)
	db "THERESA@", TRAINERTYPE_NORMAL
	db 16, SENTRET
	db -1 ; end

	; BEAUTY (16)
	db "VALERIE@", TRAINERTYPE_MOVES
	db 19, HOPPIP,     SYNTHESIS, TAIL_WHIP, TACKLE, POISONPOWDER
	db 19, SKIPLOOM,   SYNTHESIS, TAIL_WHIP, TACKLE, STUN_SPORE
	db -1 ; end

PokemaniacGroup:
	; POKEMANIAC (1)
	db "LARRY@", TRAINERTYPE_NORMAL
	db 11, SLOWPOKE
	db -1 ; end

	; POKEMANIAC (2)
	db "ANDREW@", TRAINERTYPE_NORMAL
	db 27, MAROWAK
	db 27, MAROWAK
	db -1 ; end

	; POKEMANIAC (3)
	db "CALVIN@", TRAINERTYPE_NORMAL
	db 29, KANGASKHAN
	db -1 ; end

	; POKEMANIAC (4)
	db "SHANE@", TRAINERTYPE_NORMAL
	db 18, NIDORINA
	db 18, NIDORINO
	db -1 ; end

	; POKEMANIAC (5)
	db "BEN@", TRAINERTYPE_NORMAL
	db 21, SLOWBRO
	db -1 ; end

	; POKEMANIAC (6)
	db "BRENT@", TRAINERTYPE_NORMAL
	db 21, LICKITUNG
	db -1 ; end

	; POKEMANIAC (7)
	db "RON@", TRAINERTYPE_NORMAL
	db 21, NIDOKING
	db -1 ; end

	; POKEMANIAC (8)
	db "ETHAN@", TRAINERTYPE_NORMAL
	db 34, RHYHORN
	db 34, RHYDON
	db -1 ; end

	; POKEMANIAC (9)
	db "BRENT@", TRAINERTYPE_NORMAL
	db 21, NIDORAN_F
	db 25, NIDOKING
	db -1 ; end

	; POKEMANIAC (10)
	db "BRENT@", TRAINERTYPE_NORMAL
	db 31, NIDORAN_M
	db 31, NIDORAN_F
	db 33, NIDORINA
	db 36, NIDOKING
	db -1 ; end

	; POKEMANIAC (11)
	db "ISSAC@", TRAINERTYPE_MOVES
	db 13, LICKITUNG,  LICK, SUPERSONIC, CUT, NO_MOVE
	db -1 ; end

	; POKEMANIAC (12)
	db "DONALD@", TRAINERTYPE_NORMAL
	db 11, SLOWPOKE
	db 11, SLOWPOKE
	db -1 ; end

	; POKEMANIAC (13)
	db "ZACH@", TRAINERTYPE_NORMAL
	db 30, RHYHORN
	db -1 ; end

GruntMGroup:
	; GRUNTM (1)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 15, KOFFING
	db -1 ; end

	; GRUNTM (2)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db  7, RATTATA
	db  10, ZUBAT
	db  10, ZUBAT
	db -1 ; end

	; GRUNTM (3)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 27, RATICATE
	db 27, RATICATE
	db -1 ; end

	; GRUNTM (4)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 25, GRIMER
	db 25, GRIMER
	db 28, MUK
	db -1 ; end

	; GRUNTM (5)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 23, RATTATA
	db 23, RATTATA
	db 25, RATTATA
	db 25, RATTATA
	db 25, RATTATA
	db -1 ; end

	; GRUNTM (6)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 29, ZUBAT
	db 29, ZUBAT
	db -1 ; end

	; GRUNTM (7)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 25, KOFFING
	db 25, GRIMER
	db 25, ZUBAT
	db 25, RATTATA
	db -1 ; end

	; GRUNTM (8)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 29, WEEZING
	db -1 ; end

	; GRUNTM (9)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 27, RATICATE
	db 29, KOFFING
	db -1 ; end

	; GRUNTM (10)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 24, ZUBAT
	db 27, GOLBAT
	db 24, GRIMER
	db -1 ; end

	; GRUNTM (11)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 25, MUK
	db 25, KOFFING
	db 28, RATTATA
	db -1 ; end

	; GRUNTM (12)
	db "EXECUTIVE@", TRAINERTYPE_NORMAL
	db 37, HOUNDOUR
	db -1 ; end

	; GRUNTM (13)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 30, RATTATA
	db -1 ; end

	; GRUNTM (14)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 27, RATICATE
	db 27, GOLBAT
	db -1 ; end

	; GRUNTM (15)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 29, GRIMER
	db 25, WEEZING
	db -1 ; end

	; GRUNTM (16)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 18, RATTATA
	db 18, RATTATA
	db 18, RATTATA
	db 18, RATTATA
	db -1 ; end

	; GRUNTM (17)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 20, GOLBAT
	db -1 ; end

	; GRUNTM (18)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 19, RATTATA
	db 19, ZUBAT
	db 19, RATTATA
	db -1 ; end

	; GRUNTM (19)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 20, VENONAT
	db 20, VENONAT
	db -1 ; end

	; GRUNTM (20)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 19, DROWZEE
	db 21, ZUBAT
	db -1 ; end

	; GRUNTM (21)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 18, ZUBAT
	db 19, GRIMER
	db 20, RATTATA
	db -1 ; end

	; GRUNTM (22)
	db "EXECUTIVE@", TRAINERTYPE_NORMAL
	db 40, GOLBAT
	db -1 ; end

	; GRUNTM (23)
	db "EXECUTIVE@", TRAINERTYPE_NORMAL
	db 33, KOFFING
	db -1 ; end

	; GRUNTM (24)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 28, KOFFING
	db 28, KOFFING
	db -1 ; end

	; GRUNTM (25)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 27, KOFFING
	db 27, MUK
	db -1 ; end

	; GRUNTM (26)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 16, RATTATA
	db 16, RATTATA
	db -1 ; end

	; GRUNTM (27)
	db "EXECUTIVE@", TRAINERTYPE_NORMAL
	db 24, ZUBAT
	db -1 ; end

	; GRUNTM (28)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 21, RATICATE
	db -1 ; end

	; GRUNTM (29)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db  10, RATTATA
	db  10, RATTATA
	db -1 ; end

	; GRUNTM (30)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 28, GOLBAT
	db 28, GOLBAT
	db 33, ARBOK
	db -1 ; end

	; GRUNTM (31)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 33, GOLBAT
	db -1 ; end

GentlemanGroup:
	; GENTLEMAN (1)
	db "PRESTON@", TRAINERTYPE_NORMAL
	db 20, GROWLITHE
	db 20, GROWLITHE
	db -1 ; end

	; GENTLEMAN (2)
	db "EDWARD@", TRAINERTYPE_NORMAL
	db 37, PERSIAN
	db -1 ; end

	; GENTLEMAN (3)
	db "GREGORY@", TRAINERTYPE_NORMAL
	db 41, PIKACHU
	db 37, FLAAFFY
	db -1 ; end

	; GENTLEMAN (4)
	db "VIRGIL@", TRAINERTYPE_NORMAL
	db 22, PONYTA
	db -1 ; end

	; GENTLEMAN (5)
	db "ALFRED@", TRAINERTYPE_NORMAL
	db 22, NOCTOWL
	db -1 ; end

SkierGroup:
	; SKIER (1)
	db "ROXANNE@", TRAINERTYPE_NORMAL
	db 31, JYNX
	db -1 ; end

	; SKIER (2)
	db "CLARISSA@", TRAINERTYPE_NORMAL
	db 31, DEWGONG
	db -1 ; end

TeacherGroup:
	; TEACHER (1)
	db "COLETTE@", TRAINERTYPE_NORMAL
	db 40, CLEFAIRY
	db -1 ; end

	; TEACHER (2)
	db "HILLARY@", TRAINERTYPE_NORMAL
	db 36, AIPOM
	db 40, CUBONE
	db -1 ; end

	; TEACHER (3)
	db "SHIRLEY@", TRAINERTYPE_NORMAL
	db 39, JIGGLYPUFF
	db -1 ; end

SabrinaGroup:
	; SABRINA (1)
	db "SABRINA@", TRAINERTYPE_MOVES
	db 51, ESPEON,     SAND_ATTACK, QUICK_ATTACK, SWIFT, PSYCHIC_M
	db 51, MR__MIME,   BARRIER, REFLECT, BATON_PASS, PSYCHIC_M
	db 54, ALAKAZAM,   RECOVER, FUTURE_SIGHT, PSYCHIC_M, REFLECT
	db -1 ; end

BugCatcherGroup:
	; BUG_CATCHER (1)
	db "DON@", TRAINERTYPE_NORMAL
	db  3, CATERPIE
	db  3, CATERPIE
	db -1 ; end

	; BUG_CATCHER (2)
	db "ROB@", TRAINERTYPE_NORMAL
	db 36, BEEDRILL
	db 36, BUTTERFREE
	db -1 ; end

	; BUG_CATCHER (3)
	db "ED@", TRAINERTYPE_NORMAL
	db 33, BEEDRILL
	db 33, BEEDRILL
	db 33, BEEDRILL
	db -1 ; end

	; BUG_CATCHER (4)
	db "WADE@", TRAINERTYPE_NORMAL
	db  2, CATERPIE
	db  2, CATERPIE
	db  3, WEEDLE
	db  2, CATERPIE
	db -1 ; end

	; BUG_CATCHER (5)
	db "BENNY@", TRAINERTYPE_NORMAL
	db  7, WEEDLE
	db  10, KAKUNA
	db 13, BEEDRILL
	db -1 ; end

	; BUG_CATCHER (6)
	db "AL@", TRAINERTYPE_NORMAL
	db 13, CATERPIE
	db 13, WEEDLE
	db -1 ; end

	; BUG_CATCHER (7)
	db "JOSH@", TRAINERTYPE_NORMAL
	db 14, PARAS
	db -1 ; end

	; BUG_CATCHER (8)
	db "ARNIE@", TRAINERTYPE_NORMAL
	db 16, VENONAT
	db -1 ; end

	; BUG_CATCHER (9)
	db "KEN@", TRAINERTYPE_NORMAL
	db 33, ARIADOS
	db 36, PINSIR
	db -1 ; end

	; BUG_CATCHER (10)
	db "WADE@", TRAINERTYPE_NORMAL
	db  10, METAPOD
	db  10, METAPOD
	db 11, KAKUNA
	db  10, METAPOD
	db -1 ; end

	; BUG_CATCHER (11)
	db "WADE@", TRAINERTYPE_NORMAL
	db 15, BUTTERFREE
	db 15, BUTTERFREE
	db 16, BEEDRILL
	db 15, BUTTERFREE
	db -1 ; end

	; BUG_CATCHER (12)
	db "DOUG@", TRAINERTYPE_NORMAL
	db 38, ARIADOS
	db -1 ; end

	; BUG_CATCHER (13)
	db "ARNIE@", TRAINERTYPE_NORMAL
	db 21, VENONAT
	db -1 ; end

	; BUG_CATCHER (14)
	db "ARNIE@", TRAINERTYPE_MOVES
	db 31, VENOMOTH,   DISABLE, SUPERSONIC, CONFUSION, LEECH_LIFE
	db -1 ; end

FisherGroup:
	; FISHER (1)
	db "JUSTIN@", TRAINERTYPE_NORMAL
	db  5, MAGIKARP
	db  5, MAGIKARP
	db 16, MAGIKARP
	db  5, MAGIKARP
	db -1 ; end

	; FISHER (2)
	db "RALPH@", TRAINERTYPE_NORMAL
	db 11, GOLDEEN
	db -1 ; end

	; FISHER (3)
	db "ARNOLD@", TRAINERTYPE_NORMAL
	db 38, TENTACRUEL
	db -1 ; end

	; FISHER (4)
	db "KYLE@", TRAINERTYPE_NORMAL
	db 31, SEAKING
	db 34, POLIWHIRL
	db 34, SEAKING
	db -1 ; end

	; FISHER (5)
	db "HENRY@", TRAINERTYPE_NORMAL
	db  9, POLIWAG
	db  9, POLIWAG
	db -1 ; end

	; FISHER (6)
	db "MARVIN@", TRAINERTYPE_NORMAL
	db 11, MAGIKARP
	db 11, GYARADOS
	db 16, MAGIKARP
	db 16, GYARADOS
	db -1 ; end

	; FISHER (7)
	db "CHRIS@", TRAINERTYPE_NORMAL
	db 20, QWILFISH
	db -1 ; end

	; FISHER (8)
	db "ANDRE@", TRAINERTYPE_NORMAL
	db 30, GYARADOS
	db -1 ; end

	; FISHER (9)
	db "RAYMOND@", TRAINERTYPE_NORMAL
	db 24, MAGIKARP
	db 24, MAGIKARP
	db 24, MAGIKARP
	db 24, MAGIKARP
	db -1 ; end

	; FISHER (10)
	db "WILTON@", TRAINERTYPE_NORMAL
	db 25, GOLDEEN
	db 25, GOLDEEN
	db 28, SEAKING
	db -1 ; end

	; FISHER (11)
	db "EDGAR@", TRAINERTYPE_MOVES
	db 28, REMORAID,   LOCK_ON, PSYBEAM, AURORA_BEAM, BUBBLEBEAM
	db 28, REMORAID,   LOCK_ON, PSYBEAM, AURORA_BEAM, BUBBLEBEAM
	db -1 ; end

	; FISHER (12)
	db "JONAH@", TRAINERTYPE_NORMAL
	db 28, SHELLDER
	db 32, OCTILLERY
	db 28, REMORAID
	db 32, CLOYSTER
	db -1 ; end

	; FISHER (13)
	db "MARTIN@", TRAINERTYPE_NORMAL
	db 36, REMORAID
	db 36, REMORAID
	db -1 ; end

	; FISHER (14)
	db "STEPHEN@", TRAINERTYPE_NORMAL
	db 28, MAGIKARP
	db 28, MAGIKARP
	db 34, QWILFISH
	db 34, TENTACRUEL
	db -1 ; end

	; FISHER (15)
	db "BARNEY@", TRAINERTYPE_NORMAL
	db 33, GYARADOS
	db 33, GYARADOS
	db 33, GYARADOS
	db -1 ; end

	; FISHER (16)
	db "RALPH@", TRAINERTYPE_NORMAL
	db 19, GOLDEEN
	db -1 ; end

	; FISHER (17)
	db "RALPH@", TRAINERTYPE_NORMAL
	db 19, QWILFISH
	db 21, GOLDEEN
	db -1 ; end

	; FISHER (18)
	db "CHRIS@", TRAINERTYPE_NORMAL
	db 25, QWILFISH
	db -1 ; end

	; FISHER (19)
	db "CHRIS@", TRAINERTYPE_NORMAL
	db 36, GOLDEEN
	db 36, GOLDEEN
	db 38, QWILFISH
	db -1 ; end

	; FISHER (20)
	db "WILTON@", TRAINERTYPE_NORMAL
	db 32, GOLDEEN
	db 32, GOLDEEN
	db 36, SEAKING
	db -1 ; end

	; FISHER (21)
	db "SCOTT@", TRAINERTYPE_NORMAL
	db 33, QWILFISH
	db 33, QWILFISH
	db 38, SEAKING
	db -1 ; end

	; FISHER (22)
	db "WILTON@", TRAINERTYPE_NORMAL
	db 34, GOLDEEN
	db 39, SEAKING
	db 39, SEAKING
	db -1 ; end

SwimmerMGroup:
	; SWIMMERM (1)
	db "HAROLD@", TRAINERTYPE_NORMAL
	db 36, REMORAID
	db 33, SEADRA
	db -1 ; end

	; SWIMMERM (2)
	db "SIMON@", TRAINERTYPE_NORMAL
	db 22, TENTACOOL
	db 22, TENTACOOL
	db -1 ; end

	; SWIMMERM (3)
	db "RANDALL@", TRAINERTYPE_NORMAL
	db 20, SHELLDER
	db 22, WARTORTLE
	db 20, SHELLDER
	db -1 ; end

	; SWIMMERM (4)
	db "CHARLIE@", TRAINERTYPE_NORMAL
	db 23, SHELLDER
	db 21, TENTACOOL
	db 21, TENTACRUEL
	db -1 ; end

	; SWIMMERM (5)
	db "GEORGE@", TRAINERTYPE_NORMAL
	db 18, TENTACOOL
	db 19, TENTACOOL
	db 18, TENTACOOL
	db 21, STARYU
	db 19, TENTACOOL
	db 21, REMORAID
	db -1 ; end

	; SWIMMERM (6)
	db "BERKE@", TRAINERTYPE_NORMAL
	db 25, QWILFISH
	db -1 ; end

	; SWIMMERM (7)
	db "KIRK@", TRAINERTYPE_NORMAL
	db 22, GYARADOS
	db 22, GYARADOS
	db -1 ; end

	; SWIMMERM (8)
	db "MATHEW@", TRAINERTYPE_NORMAL
	db 25, KRABBY
	db -1 ; end

	; SWIMMERM (9)
	db "HAL@", TRAINERTYPE_NORMAL
	db 27, SEEL
	db 28, DEWGONG
	db 27, SEEL
	db -1 ; end

	; SWIMMERM (10)
	db "PATON@", TRAINERTYPE_NORMAL
	db 29, PILOSWINE
	db 29, PILOSWINE
	db -1 ; end

	; SWIMMERM (11)
	db "DARYL@", TRAINERTYPE_NORMAL
	db 27, SHELLDER
	db 28, CLOYSTER
	db 27, SHELLDER
	db -1 ; end

	; SWIMMERM (12)
	db "WALTER@", TRAINERTYPE_NORMAL
	db 16, HORSEA
	db 16, HORSEA
	db 22, SEADRA
	db -1 ; end

	; SWIMMERM (13)
	db "TONY@", TRAINERTYPE_NORMAL
	db 14, STARYU
	db 20, STARMIE
	db 18, HORSEA
	db -1 ; end

	; SWIMMERM (14)
	db "JEROME@", TRAINERTYPE_NORMAL
	db 29, SEADRA
	db 31, TENTACOOL
	db 33, TENTACRUEL
	db 31, GOLDEEN
	db -1 ; end

	; SWIMMERM (15)
	db "TUCKER@", TRAINERTYPE_NORMAL
	db 33, SHELLDER
	db 38, CLOYSTER
	db -1 ; end

	; SWIMMERM (16)
	db "RICK@", TRAINERTYPE_NORMAL
	db 14, STARYU
	db 20, STARMIE
	db 18, HORSEA
	db -1 ; end

	; SWIMMERM (17)
	db "CAMERON@", TRAINERTYPE_NORMAL
	db 38, MARILL
	db -1 ; end

	; SWIMMERM (18)
	db "SETH@", TRAINERTYPE_NORMAL
	db 32, QUAGSIRE
	db 32, OCTILLERY
	db 36, QUAGSIRE
	db -1 ; end

	; SWIMMERM (19)
	db "JAMES@", TRAINERTYPE_NORMAL
	db 14, STARYU
	db 20, STARMIE
	db 18, HORSEA
	db -1 ; end

	; SWIMMERM (20)
	db "LEWIS@", TRAINERTYPE_NORMAL
	db 14, STARYU
	db 20, STARMIE
	db 18, HORSEA
	db -1 ; end

	; SWIMMERM (21)
	db "PARKER@", TRAINERTYPE_NORMAL
	db 36, HORSEA
	db 36, HORSEA
	db 39, SEADRA
	db -1 ; end

SwimmerFGroup:
	; SWIMMERF (1)
	db "ELAINE@", TRAINERTYPE_NORMAL
	db 23, STARYU
	db -1 ; end

	; SWIMMERF (2)
	db "PAULA@", TRAINERTYPE_NORMAL
	db 21, STARYU
	db 21, SHELLDER
	db -1 ; end

	; SWIMMERF (3)
	db "KAYLEE@", TRAINERTYPE_NORMAL
	db 20, GOLDEEN
	db 22, GOLDEEN
	db 22, SEAKING
	db -1 ; end

	; SWIMMERF (4)
	db "SUSIE@", TRAINERTYPE_MOVES
	db 22, PSYDUCK,    SCRATCH, TAIL_WHIP, DISABLE, CONFUSION
	db 24, GOLDEEN,    PECK, TAIL_WHIP, SUPERSONIC, HORN_ATTACK
	db -1 ; end

	; SWIMMERF (5)
	db "DENISE@", TRAINERTYPE_NORMAL
	db 24, SEEL
	db -1 ; end

	; SWIMMERF (6)
	db "KARA@", TRAINERTYPE_NORMAL
	db 22, STARYU
	db 22, STARMIE
	db -1 ; end

	; SWIMMERF (7)
	db "WENDY@", TRAINERTYPE_MOVES
	db 23, HORSEA,     BUBBLE, SMOKESCREEN, LEER, WATER_GUN
	db 23, HORSEA,     DRAGON_RAGE, SMOKESCREEN, LEER, WATER_GUN
	db -1 ; end

	; SWIMMERF (8)
	db "LISA@", TRAINERTYPE_NORMAL
	db 31, JYNX
	db -1 ; end

	; SWIMMERF (9)
	db "JILL@", TRAINERTYPE_NORMAL
	db 31, DEWGONG
	db -1 ; end

	; SWIMMERF (10)
	db "MARY@", TRAINERTYPE_NORMAL
	db 22, SEAKING
	db -1 ; end

	; SWIMMERF (11)
	db "KATIE@", TRAINERTYPE_NORMAL
	db 37, DEWGONG
	db -1 ; end

	; SWIMMERF (12)
	db "DAWN@", TRAINERTYPE_NORMAL
	db 38, SEAKING
	db -1 ; end

	; SWIMMERF (13)
	db "TARA@", TRAINERTYPE_NORMAL
	db 22, SEAKING
	db -1 ; end

	; SWIMMERF (14)
	db "NICOLE@", TRAINERTYPE_NORMAL
	db 32, MARILL
	db 32, MARILL
	db 36, LAPRAS
	db -1 ; end

	; SWIMMERF (15)
	db "LORI@", TRAINERTYPE_NORMAL
	db 36, STARMIE
	db 36, STARMIE
	db -1 ; end

	; SWIMMERF (16)
	db "JODY@", TRAINERTYPE_NORMAL
	db 22, SEAKING
	db -1 ; end

	; SWIMMERF (17)
	db "NIKKI@", TRAINERTYPE_NORMAL
	db 31, SEEL
	db 31, SEEL
	db 31, SEEL
	db 31, DEWGONG
	db -1 ; end

	; SWIMMERF (18)
	db "DIANA@", TRAINERTYPE_NORMAL
	db 41, GOLDUCK
	db -1 ; end

	; SWIMMERF (19)
	db "BRIANA@", TRAINERTYPE_NORMAL
	db 39, SEAKING
	db 39, SEAKING
	db -1 ; end

SailorGroup:
	; SAILOR (1)
	db "EUGENE@", TRAINERTYPE_NORMAL
	db 19, POLIWHIRL
	db 19, RATICATE
	db 21, KRABBY
	db -1 ; end

	; SAILOR (2)
	db "HUEY@", TRAINERTYPE_NORMAL
	db 20, POLIWAG
	db 20, POLIWHIRL
	db -1 ; end

	; SAILOR (3)
	db "TERRELL@", TRAINERTYPE_NORMAL
	db 22, POLIWHIRL
	db -1 ; end

	; SAILOR (4)
	db "KENT@", TRAINERTYPE_MOVES
	db 20, KRABBY,     BUBBLE, LEER, VICEGRIP, HARDEN
	db 22, KRABBY,     BUBBLEBEAM, LEER, VICEGRIP, HARDEN
	db -1 ; end

	; SAILOR (5)
	db "ERNEST@", TRAINERTYPE_NORMAL
	db 20, MACHOP
	db 20, MACHOP
	db 20, POLIWHIRL
	db -1 ; end

	; SAILOR (6)
	db "JEFF@", TRAINERTYPE_NORMAL
	db 36, RATICATE
	db 36, RATICATE
	db -1 ; end

	; SAILOR (7)
	db "GARRETT@", TRAINERTYPE_NORMAL
	db 38, KINGLER
	db -1 ; end

	; SAILOR (8)
	db "KENNETH@", TRAINERTYPE_NORMAL
	db 31, MACHOP
	db 31, MACHOP
	db 31, POLIWRATH
	db 31, MACHOP
	db -1 ; end

	; SAILOR (9)
	db "STANLY@", TRAINERTYPE_NORMAL
	db 34, MACHOP
	db 37, MACHOKE
	db 29, PSYDUCK
	db -1 ; end

	; SAILOR (10)
	db "HARRY@", TRAINERTYPE_NORMAL
	db 21, WOOPER
	db -1 ; end

	; SAILOR (11)
	db "HUEY@", TRAINERTYPE_NORMAL
	db 31, POLIWHIRL
	db 31, POLIWHIRL
	db -1 ; end

	; SAILOR (12)
	db "HUEY@", TRAINERTYPE_NORMAL
	db 38, POLIWHIRL
	db 38, POLIWRATH
	db -1 ; end

SuperNerdGroup:
	; SUPER_NERD (1)
	db "ERIC@", TRAINERTYPE_NORMAL
	db 22, GRIMER
	db -1 ; end

	; SUPER_NERD (2)
	db "ERIC@", TRAINERTYPE_NORMAL
	db 12, GRIMER
	db 12, GRIMER
	db -1 ; end

	; SUPER_NERD (3)
	db "GREGG@", TRAINERTYPE_NORMAL
	db 22, MAGNEMITE
	db 22, MAGNEMITE
	db 22, MAGNEMITE
	db -1 ; end

	; SUPER_NERD (4)
	db "JAY@", TRAINERTYPE_NORMAL
	db 24, KOFFING
	db 24, KOFFING
	db -1 ; end

	; SUPER_NERD (5)
	db "DAVE@", TRAINERTYPE_NORMAL
	db 27, DITTO
	db -1 ; end

	; SUPER_NERD (6)
	db "SAM@", TRAINERTYPE_NORMAL
	db 38, GRIMER
	db 38, MUK
	db -1 ; end

	; SUPER_NERD (7)
	db "TOM@", TRAINERTYPE_NORMAL
	db 36, MAGNEMITE
	db 36, MAGNEMITE
	db 36, MAGNEMITE
	db -1 ; end

	; SUPER_NERD (8)
	db "PAT@", TRAINERTYPE_NORMAL
	db 40, PORYGON
	db -1 ; end

	; SUPER_NERD (9)
	db "SHAWN@", TRAINERTYPE_NORMAL
	db 34, MAGNEMITE
	db 37, MUK
	db 34, MAGNEMITE
	db -1 ; end

	; SUPER_NERD (10)
	db "TERU@", TRAINERTYPE_NORMAL
	db  7, MAGNEMITE
	db 12, VOLTORB
	db  7, MAGNEMITE
	db  10, MAGNEMITE
	db -1 ; end

	; SUPER_NERD (11)
	db "RUSS@", TRAINERTYPE_NORMAL
	db 30, MAGNEMITE
	db 30, MAGNEMITE
	db 30, MAGNEMITE
	db -1 ; end

	; SUPER_NERD (12)
	db "NORTON@", TRAINERTYPE_MOVES
	db 33, PORYGON,    CONVERSION, CONVERSION33, RECOVER, TRI_ATTACK
	db -1 ; end

Rival2Group:
	; RIVAL2 (1)
	db "?@", TRAINERTYPE_MOVES
	db 46, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 47, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 46, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 48, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 48, ALAKAZAM,   DISABLE, RECOVER, FUTURE_SIGHT, PSYCHIC_M
	db 50, MEGANIUM,   RAZOR_LEAF, POISONPOWDER, BODY_SLAM, LIGHT_SCREEN
	db -1 ; end

	; RIVAL2 (2)
	db "?@", TRAINERTYPE_MOVES
	db 46, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 47, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 46, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 48, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 48, ALAKAZAM,   DISABLE, RECOVER, FUTURE_SIGHT, PSYCHIC_M
	db 50, TYPHLOSION, SMOKESCREEN, QUICK_ATTACK, FLAME_WHEEL, SWIFT
	db -1 ; end

	; RIVAL2 (3)
	db "?@", TRAINERTYPE_MOVES
	db 46, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 47, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db 46, MAGNETON,   THUNDERSHOCK, SONICBOOM, THUNDER_WAVE, SWIFT
	db 48, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 48, ALAKAZAM,   DISABLE, RECOVER, FUTURE_SIGHT, PSYCHIC_M
	db 50, FERALIGATR, RAGE, WATER_GUN, SCARY_FACE, SLASH
	db -1 ; end

	; RIVAL2 (4)
	db "?@", TRAINERTYPE_MOVES
	db 50, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 54, CROBAT,     TOXIC, BITE, CONFUSE_RAY, WING_ATTACK
	db 50, MAGNETON,   THUNDER, SONICBOOM, THUNDER_WAVE, SWIFT
	db 51, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 51, ALAKAZAM,   RECOVER, FUTURE_SIGHT, PSYCHIC_M, REFLECT
	db 56, MEGANIUM,   GIGA_DRAIN, BODY_SLAM, LIGHT_SCREEN, SAFEGUARD
	db -1 ; end

	; RIVAL2 (5)
	db "?@", TRAINERTYPE_MOVES
	db 50, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 54, CROBAT,     TOXIC, BITE, CONFUSE_RAY, WING_ATTACK
	db 50, MAGNETON,   THUNDER, SONICBOOM, THUNDER_WAVE, SWIFT
	db 51, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 51, ALAKAZAM,   RECOVER, FUTURE_SIGHT, PSYCHIC_M, REFLECT
	db 56, TYPHLOSION, SMOKESCREEN, QUICK_ATTACK, FIRE_BLAST, SWIFT
	db -1 ; end

	; RIVAL2 (6)
	db "?@", TRAINERTYPE_MOVES
	db 50, SNEASEL,    QUICK_ATTACK, SCREECH, FAINT_ATTACK, FURY_CUTTER
	db 54, CROBAT,     TOXIC, BITE, CONFUSE_RAY, WING_ATTACK
	db 50, MAGNETON,   THUNDER, SONICBOOM, THUNDER_WAVE, SWIFT
	db 51, GENGAR,     MEAN_LOOK, CURSE, SHADOW_BALL, CONFUSE_RAY
	db 51, ALAKAZAM,   RECOVER, FUTURE_SIGHT, PSYCHIC_M, REFLECT
	db 56, FERALIGATR, SURF, RAIN_DANCE, SLASH, SCREECH
	db -1 ; end

GuitaristGroup:
	; GUITARIST (1)
	db "CLYDE@", TRAINERTYPE_NORMAL
	db 38, ELECTABUZZ
	db -1 ; end

	; GUITARIST (2)
	db "VINCENT@", TRAINERTYPE_NORMAL
	db 30, MAGNEMITE
	db 37, VOLTORB
	db 36, MAGNEMITE
	db 36, MAGNEMITE
	db -1 ; end

HikerGroup:
	; HIKER (1)
	db "ANTHONY@", TRAINERTYPE_NORMAL
	db 18, GEODUDE
	db 20, MACHAMP
	db -1 ; end

	; HIKER (2)
	db "RUSSELL@", TRAINERTYPE_NORMAL
	db  4, GEODUDE
	db  6, GEODUDE
	db  9, GEODUDE
	db -1 ; end

	; HIKER (3)
	db "PHILLIP@", TRAINERTYPE_NORMAL
	db 25, GEODUDE
	db 25, GEODUDE
	db 25, GRAVELER
	db -1 ; end

	; HIKER (4)
	db "LEONARD@", TRAINERTYPE_NORMAL
	db 25, GEODUDE
	db 28, MACHOP
	db -1 ; end

	; HIKER (5)
	db "ANTHONY@", TRAINERTYPE_NORMAL
	db 12, GEODUDE
	db 12, MACHOP
	db -1 ; end

	; HIKER (6)
	db "BENJAMIN@", TRAINERTYPE_NORMAL
	db 15, DIGLETT
	db 15, GEODUDE
	db 18, DUGTRIO
	db -1 ; end

	; HIKER (7)
	db "ERIK@", TRAINERTYPE_NORMAL
	db 27, MACHOP
	db 30, GRAVELER
	db 30, MACHOP
	db -1 ; end

	; HIKER (8)
	db "MICHAEL@", TRAINERTYPE_NORMAL
	db 28, GEODUDE
	db 28, GRAVELER
	db 28, GOLEM
	db -1 ; end

	; HIKER (9)
	db "PARRY@", TRAINERTYPE_NORMAL
	db 38, ONIX
	db -1 ; end

	; HIKER (10)
	db "TIMOTHY@", TRAINERTYPE_MOVES
	db 30, DIGLETT,    MAGNITUDE, DIG, SAND_ATTACK, SLASH
	db 30, DUGTRIO,    MAGNITUDE, DIG, SAND_ATTACK, SLASH
	db -1 ; end

	; HIKER (11)
	db "BAILEY@", TRAINERTYPE_NORMAL
	db 14, GEODUDE
	db 14, GEODUDE
	db 14, GEODUDE
	db 14, GEODUDE
	db 14, GEODUDE
	db -1 ; end

	; HIKER (12)
	db "ANTHONY@", TRAINERTYPE_NORMAL
	db 28, GRAVELER
	db 30, GRAVELER
	db 32, MACHOKE
	db -1 ; end

	; HIKER (13)
	db "TIM@", TRAINERTYPE_NORMAL
	db 34, GRAVELER
	db 34, GRAVELER
	db 34, GRAVELER
	db -1 ; end

	; HIKER (14)
	db "NOLAND@", TRAINERTYPE_NORMAL
	db 34, SANDSLASH
	db 37, GOLEM
	db -1 ; end

	; HIKER (15)
	db "SIDNEY@", TRAINERTYPE_NORMAL
	db 38, DUGTRIO
	db 36, ONIX
	db -1 ; end

	; HIKER (16)
	db "KENNY@", TRAINERTYPE_NORMAL
	db 30, SANDSLASH
	db 32, GRAVELER
	db 34, GOLEM
	db 32, GRAVELER
	db -1 ; end

	; HIKER (17)
	db "JIM@", TRAINERTYPE_NORMAL
	db 39, MACHAMP
	db -1 ; end

	; HIKER (18)
	db "DANIEL@", TRAINERTYPE_NORMAL
	db 12, ONIX
	db -1 ; end

	; HIKER (19)
	db "PARRY@", TRAINERTYPE_NORMAL
	db 42, ONIX
	db -1 ; end

	; HIKER (20)
	db "PARRY@", TRAINERTYPE_NORMAL
	db 32, ONIX
	db -1 ; end

BikerGroup:
	; BIKER (1)
	db "KAZU@", TRAINERTYPE_NORMAL
	db 22, KOFFING
	db 22, KOFFING
	db 22, KOFFING
	db -1 ; end

	; BIKER (2)
	db "KAZU@", TRAINERTYPE_NORMAL
	db 22, KOFFING
	db 22, KOFFING
	db 22, KOFFING
	db -1 ; end

	; BIKER (3)
	db "DWAYNE@", TRAINERTYPE_NORMAL
	db 30, KOFFING
	db 31, KOFFING
	db 32, KOFFING
	db 33, KOFFING
	db -1 ; end

	; BIKER (4)
	db "HARRIS@", TRAINERTYPE_NORMAL
	db 38, FLAREON
	db -1 ; end

	; BIKER (5)
	db "ZEKE@", TRAINERTYPE_NORMAL
	db 36, KOFFING
	db 36, KOFFING
	db -1 ; end

	; BIKER (6)
	db "CHARLES@", TRAINERTYPE_NORMAL
	db 33, KOFFING
	db 33, CHARMELEON
	db 33, WEEZING
	db -1 ; end

	; BIKER (7)
	db "RILEY@", TRAINERTYPE_NORMAL
	db 38, WEEZING
	db -1 ; end

	; BIKER (8)
	db "JOEL@", TRAINERTYPE_NORMAL
	db 36, MAGMAR
	db 36, MAGMAR
	db -1 ; end

	; BIKER (9)
	db "GLENN@", TRAINERTYPE_NORMAL
	db 31, KOFFING
	db 33, MAGMAR
	db 36, WEEZING
	db -1 ; end

BlaineGroup:
	; BLAINE (1)
	db "BLAINE@", TRAINERTYPE_MOVES
	db 50, MAGCARGO,   CURSE, SMOG, FLAMETHROWER, ROCK_SLIDE
	db 50, MAGMAR,     THUNDERPUNCH, FIRE_PUNCH, SUNNY_DAY, CONFUSE_RAY
	db 56, RAPIDASH,   QUICK_ATTACK, FIRE_SPIN, FURY_ATTACK, FIRE_BLAST
	db -1 ; end

BurglarGroup:
	; BURGLAR (1)
	db "DUNCAN@", TRAINERTYPE_NORMAL
	db 25, KOFFING
	db 28, MAGMAR
	db 25, KOFFING
	db -1 ; end

	; BURGLAR (2)
	db "EDDIE@", TRAINERTYPE_MOVES
	db 29, GROWLITHE,  ROAR, EMBER, LEER, TAKE_DOWN
	db 27, KOFFING,    TACKLE, SMOG, SLUDGE, SMOKESCREEN
	db -1 ; end

	; BURGLAR (3)
	db "COREY@", TRAINERTYPE_NORMAL
	db 28, KOFFING
	db 31, MAGMAR
	db 28, KOFFING
	db 33, KOFFING
	db -1 ; end

FirebreatherGroup:
	; FIREBREATHER (1)
	db "OTIS@", TRAINERTYPE_NORMAL
	db 32, MAGMAR
	db 36, WEEZING
	db 32, MAGMAR
	db -1 ; end

	; FIREBREATHER (2)
	db "DICK@", TRAINERTYPE_NORMAL
	db 19, CHARMELEON
	db -1 ; end

	; FIREBREATHER (3)
	db "NED@", TRAINERTYPE_NORMAL
	db 16, KOFFING
	db 18, GROWLITHE
	db 16, KOFFING
	db -1 ; end

	; FIREBREATHER (4)
	db "BURT@", TRAINERTYPE_NORMAL
	db 36, KOFFING
	db 36, SLUGMA
	db -1 ; end

	; FIREBREATHER (5)
	db "BILL@", TRAINERTYPE_NORMAL
	db  6, KOFFING
	db  6, KOFFING
	db -1 ; end

	; FIREBREATHER (6)
	db "WALT@", TRAINERTYPE_NORMAL
	db 12, MAGMAR
	db 14, MAGMAR
	db -1 ; end

	; FIREBREATHER (7)
	db "RAY@", TRAINERTYPE_NORMAL
	db  10, VULPIX
	db -1 ; end

	; FIREBREATHER (8)
	db "LYLE@", TRAINERTYPE_NORMAL
	db 31, KOFFING
	db 34, FLAREON
	db 31, KOFFING
	db -1 ; end

JugglerGroup:
	; JUGGLER (1)
	db "IRWIN@", TRAINERTYPE_NORMAL
	db  2, VOLTORB
	db  6, VOLTORB
	db 11, VOLTORB
	db 15, VOLTORB
	db -1 ; end

	; JUGGLER (2)
	db "FRITZ@", TRAINERTYPE_NORMAL
	db 32, MR__MIME
	db 32, MAGMAR
	db 32, MACHOKE
	db -1 ; end

	; JUGGLER (3)
	db "HORTON@", TRAINERTYPE_NORMAL
	db 37, ELECTRODE
	db 37, ELECTRODE
	db 37, ELECTRODE
	db 37, ELECTRODE
	db -1 ; end

	; JUGGLER (4)
	db "IRWIN@", TRAINERTYPE_NORMAL
	db  6, VOLTORB
	db 11, VOLTORB
	db 15, VOLTORB
	db 20, VOLTORB
	db -1 ; end

	; JUGGLER (5)
	db "IRWIN@", TRAINERTYPE_NORMAL
	db 20, VOLTORB
	db 24, VOLTORB
	db 29, VOLTORB
	db 33, ELECTRODE
	db -1 ; end

BlackbeltGroup:
	; BLACKBELT_T (1)
	db "KENJI@", TRAINERTYPE_NORMAL
	db 30, ONIX
	db 33, HITMONLEE
	db 30, ONIX
	db 36, MACHOKE
	db -1 ; end

	; BLACKBELT_T (2)
	db "YOSHI@", TRAINERTYPE_MOVES
	db 30, HITMONLEE,  DOUBLE_KICK, MEDITATE, JUMP_KICK, FOCUS_ENERGY
	db -1 ; end

	; BLACKBELT_T (3)
	db "KENJI@", TRAINERTYPE_NORMAL
	db 33, ONIX
	db 41, MACHAMP
	db 33, ONIX
	db 39, HITMONLEE
	db -1 ; end

	; BLACKBELT_T (4)
	db "LAO@", TRAINERTYPE_MOVES
	db 30, HITMONCHAN, COMET_PUNCH, THUNDERPUNCH, ICE_PUNCH, FIRE_PUNCH
	db -1 ; end

	; BLACKBELT_T (5)
	db "NOB@", TRAINERTYPE_MOVES
	db 28, MACHOP,     LEER, FOCUS_ENERGY, KARATE_CHOP, SEISMIC_TOSS
	db 28, MACHOKE,    LEER, KARATE_CHOP, SEISMIC_TOSS, ROCK_SLIDE
	db -1 ; end

	; BLACKBELT_T (6)
	db "KIYO@", TRAINERTYPE_NORMAL
	db 38, HITMONLEE
	db 38, HITMONCHAN
	db -1 ; end

	; BLACKBELT_T (7)
	db "LUNG@", TRAINERTYPE_NORMAL
	db 25, MANKEY
	db 25, MANKEY
	db 28, PRIMEAPE
	db -1 ; end

	; BLACKBELT_T (8)
	db "KENJI@", TRAINERTYPE_NORMAL
	db 31, MACHOKE
	db -1 ; end

	; BLACKBELT_T (9)
	db "WAI@", TRAINERTYPE_NORMAL
	db 33, MACHOKE
	db 36, MACHOKE
	db 38, MACHOKE
	db -1 ; end

ExecutiveMGroup:
	; EXECUTIVEM (1)
	db "EXECUTIVE@", TRAINERTYPE_MOVES
	db 37, HOUNDOUR,   EMBER, ROAR, BITE, FAINT_ATTACK
	db 37, KOFFING,    TACKLE, SLUDGE, SMOKESCREEN, HAZE
	db 39, HOUNDOOM,   EMBER, SMOG, BITE, FAINT_ATTACK
	db -1 ; end

	; EXECUTIVEM (2)
	db "EXECUTIVE@", TRAINERTYPE_MOVES
	db 40, GOLBAT,     LEECH_LIFE, BITE, CONFUSE_RAY, WING_ATTACK
	db -1 ; end

	; EXECUTIVEM (3)
	db "EXECUTIVE@", TRAINERTYPE_MOVES
	db 33, KOFFING,    TACKLE, SELFDESTRUCT, SLUDGE, SMOKESCREEN
	db 33, KOFFING,    TACKLE, SELFDESTRUCT, SLUDGE, SMOKESCREEN
	db 33, KOFFING,    TACKLE, SELFDESTRUCT, SLUDGE, SMOKESCREEN
	db 36, WEEZING,    TACKLE, EXPLOSION, SLUDGE, SMOKESCREEN
	db 33, KOFFING,    TACKLE, SELFDESTRUCT, SLUDGE, SMOKESCREEN
	db 33, KOFFING,    TACKLE, SMOG, SLUDGE, SMOKESCREEN
	db -1 ; end

	; EXECUTIVEM (4)
	db "EXECUTIVE@", TRAINERTYPE_NORMAL
	db 24, ZUBAT
	db 27, RATICATE
	db 24, KOFFING
	db -1 ; end

PsychicGroup:
	; PSYCHIC_T (1)
	db "NATHAN@", TRAINERTYPE_NORMAL
	db 29, GIRAFARIG
	db -1 ; end

	; PSYCHIC_T (2)
	db "FRANKLIN@", TRAINERTYPE_NORMAL
	db 41, KADABRA
	db -1 ; end

	; PSYCHIC_T (3)
	db "HERMAN@", TRAINERTYPE_NORMAL
	db 33, EXEGGCUTE
	db 33, EXEGGCUTE
	db 33, EXEGGUTOR
	db -1 ; end

	; PSYCHIC_T (4)
	db "FIDEL@", TRAINERTYPE_NORMAL
	db 38, XATU
	db -1 ; end

	; PSYCHIC_T (5)
	db "GREG@", TRAINERTYPE_MOVES
	db 19, DROWZEE,    HYPNOSIS, DISABLE, DREAM_EATER, NO_MOVE
	db -1 ; end

	; PSYCHIC_T (6)
	db "NORMAN@", TRAINERTYPE_MOVES
	db 19, SLOWPOKE,   TACKLE, GROWL, WATER_GUN, NO_MOVE
	db 22, SLOWPOKE,   CURSE, BODY_SLAM, WATER_GUN, CONFUSION
	db -1 ; end

	; PSYCHIC_T (7)
	db "MARK@", TRAINERTYPE_MOVES
	db 14, ABRA,       TELEPORT, FLASH, NO_MOVE, NO_MOVE
	db 14, ABRA,       TELEPORT, FLASH, NO_MOVE, NO_MOVE
	db 16, KADABRA,    TELEPORT, KINESIS, CONFUSION, NO_MOVE
	db -1 ; end

	; PSYCHIC_T (8)
	db "PHIL@", TRAINERTYPE_MOVES
	db 27, NATU,       LEER, NIGHT_SHADE, FUTURE_SIGHT, CONFUSE_RAY
	db 29, KADABRA,    DISABLE, PSYBEAM, RECOVER, FUTURE_SIGHT
	db -1 ; end

	; PSYCHIC_T (9)
	db "RICHARD@", TRAINERTYPE_NORMAL
	db 40, ESPEON
	db -1 ; end

	; PSYCHIC_T (10)
	db "GILBERT@", TRAINERTYPE_NORMAL
	db 33, STARMIE
	db 33, EXEGGCUTE
	db 38, GIRAFARIG
	db -1 ; end

	; PSYCHIC_T (11)
	db "JARED@", TRAINERTYPE_NORMAL
	db 36, MR__MIME
	db 36, EXEGGCUTE
	db 39, EXEGGCUTE
	db -1 ; end

	; PSYCHIC_T (12)
	db "RODNEY@", TRAINERTYPE_NORMAL
	db 32, DROWZEE
	db 37, HYPNO
	db -1 ; end

PicnickerGroup:
	; PICNICKER (1)
	db "LIZ@", TRAINERTYPE_NORMAL
	db  10, NIDORAN_F
	db -1 ; end

	; PICNICKER (2)
	db "GINA@", TRAINERTYPE_NORMAL
	db  10, HOPPIP
	db  10, HOPPIP
	db 13, BULBASAUR
	db -1 ; end

	; PICNICKER (3)
	db "BROOKE@", TRAINERTYPE_MOVES
	db 18, PIKACHU,    THUNDERSHOCK, GROWL, QUICK_ATTACK, DOUBLE_TEAM
	db -1 ; end

	; PICNICKER (4)
	db "KIM@", TRAINERTYPE_NORMAL
	db 16, VULPIX
	db -1 ; end

	; PICNICKER (5)
	db "CINDY@", TRAINERTYPE_NORMAL
	db 40, NIDOQUEEN
	db -1 ; end

	; PICNICKER (6)
	db "HOPE@", TRAINERTYPE_NORMAL
	db 38, FLAAFFY
	db -1 ; end

	; PICNICKER (7)
	db "SHARON@", TRAINERTYPE_NORMAL
	db 34, FURRET
	db 37, RAPIDASH
	db -1 ; end

	; PICNICKER (8)
	db "DEBRA@", TRAINERTYPE_NORMAL
	db 37, SEAKING
	db -1 ; end

	; PICNICKER (9)
	db "GINA@", TRAINERTYPE_NORMAL
	db 15, HOPPIP
	db 15, HOPPIP
	db 19, IVYSAUR
	db -1 ; end

	; PICNICKER (10)
	db "ERIN@", TRAINERTYPE_NORMAL
	db 18, PONYTA
	db 18, PONYTA
	db -1 ; end

	; PICNICKER (11)
	db "LIZ@", TRAINERTYPE_NORMAL
	db 16, WEEPINBELL
	db 16, NIDORINA
	db -1 ; end

	; PICNICKER (12)
	db "LIZ@", TRAINERTYPE_NORMAL
	db 21, WEEPINBELL
	db 21, NIDORINO
	db 23, NIDOQUEEN
	db -1 ; end

	; PICNICKER (13)
	db "HEIDI@", TRAINERTYPE_NORMAL
	db 36, SKIPLOOM
	db 36, SKIPLOOM
	db -1 ; end

	; PICNICKER (14)
	db "EDNA@", TRAINERTYPE_NORMAL
	db 33, NIDORINA
	db 38, RAICHU
	db -1 ; end

	; PICNICKER (15)
	db "GINA@", TRAINERTYPE_NORMAL
	db 29, SKIPLOOM
	db 29, SKIPLOOM
	db 32, IVYSAUR
	db -1 ; end

	; PICNICKER (16)
	db "TIFFANY@", TRAINERTYPE_MOVES
	db 34, CLEFAIRY,   ENCORE, SING, DOUBLESLAP, MINIMIZE
	db -1 ; end

	; PICNICKER (17)
	db "TIFFANY@", TRAINERTYPE_MOVES
	db 41, CLEFAIRY,   ENCORE, DOUBLESLAP, MINIMIZE, METRONOME
	db -1 ; end

	; PICNICKER (18)
	db "ERIN@", TRAINERTYPE_NORMAL
	db 36, PONYTA
	db 36, PONYTA
	db -1 ; end

	; PICNICKER (19)
	db "TANYA@", TRAINERTYPE_NORMAL
	db 41, EXEGGUTOR
	db -1 ; end

	; PICNICKER (20)
	db "TIFFANY@", TRAINERTYPE_MOVES
	db 22, CLEFAIRY,   ENCORE, SING, DOUBLESLAP, MINIMIZE
	db -1 ; end

	; PICNICKER (21)
	db "ERIN@", TRAINERTYPE_NORMAL
	db 40, PONYTA
	db 40, PONYTA
	db -1 ; end

CamperGroup:
	; CAMPER (1)
	db "ROLAND@", TRAINERTYPE_NORMAL
	db  10, NIDORAN_M
	db -1 ; end

	; CAMPER (2)
	db "TODD@", TRAINERTYPE_NORMAL
	db 15, PSYDUCK
	db -1 ; end

	; CAMPER (3)
	db "IVAN@", TRAINERTYPE_NORMAL
	db 11, DIGLETT
	db 11, ZUBAT
	db 15, DIGLETT
	db -1 ; end

	; CAMPER (4)
	db "ELLIOT@", TRAINERTYPE_NORMAL
	db 14, SANDSHREW
	db 16, MARILL
	db -1 ; end

	; CAMPER (5)
	db "BARRY@", TRAINERTYPE_NORMAL
	db 40, NIDOKING
	db -1 ; end

	; CAMPER (6)
	db "LLOYD@", TRAINERTYPE_NORMAL
	db 38, NIDOKING
	db -1 ; end

	; CAMPER (7)
	db "DEAN@", TRAINERTYPE_NORMAL
	db 37, GOLDUCK
	db 34, SANDSLASH
	db -1 ; end

	; CAMPER (8)
	db "SID@", TRAINERTYPE_NORMAL
	db 36, DUGTRIO
	db 32, PRIMEAPE
	db 32, POLIWRATH
	db -1 ; end

	; CAMPER (9)
	db "HARVEY@", TRAINERTYPE_NORMAL
	db 16, NIDORINO
	db -1 ; end

	; CAMPER (10)
	db "DALE@", TRAINERTYPE_NORMAL
	db 16, NIDORINO
	db -1 ; end

	; CAMPER (11)
	db "TED@", TRAINERTYPE_NORMAL
	db 19, MANKEY
	db -1 ; end

	; CAMPER (12)
	db "TODD@", TRAINERTYPE_NORMAL
	db 19, GEODUDE
	db 19, GEODUDE
	db 25, PSYDUCK
	db -1 ; end

	; CAMPER (13)
	db "TODD@", TRAINERTYPE_NORMAL
	db 25, GEODUDE
	db 25, GEODUDE
	db 29, PSYDUCK
	db -1 ; end

	; CAMPER (14)
	db "THOMAS@", TRAINERTYPE_NORMAL
	db 37, GRAVELER
	db 40, GRAVELER
	db 45, GOLBAT
	db 47, GOLDUCK
	db -1 ; end

	; CAMPER (15)
	db "LEROY@", TRAINERTYPE_NORMAL
	db 37, GRAVELER
	db 40, GRAVELER
	db 45, GOLBAT
	db 47, GOLDUCK
	db -1 ; end

	; CAMPER (16)
	db "DAVID@", TRAINERTYPE_NORMAL
	db 37, GRAVELER
	db 40, GRAVELER
	db 45, GOLBAT
	db 47, GOLDUCK
	db -1 ; end

	; CAMPER (17)
	db "JOHN@", TRAINERTYPE_NORMAL
	db 37, GRAVELER
	db 40, GRAVELER
	db 45, GOLBAT
	db 47, GOLDUCK
	db -1 ; end

	; CAMPER (18)
	db "JERRY@", TRAINERTYPE_NORMAL
	db 41, SANDSLASH
	db -1 ; end

	; CAMPER (19)
	db "SPENCER@", TRAINERTYPE_NORMAL
	db 19, SANDSHREW
	db 19, SANDSLASH
	db 21, ZUBAT
	db -1 ; end

ExecutiveFGroup:
	; EXECUTIVEF (1)
	db "EXECUTIVE@", TRAINERTYPE_MOVES
	db 36, ARBOK,      WRAP, POISON_STING, BITE, GLARE
	db 36, VILEPLUME,  ABSORB, SWEET_SCENT, SLEEP_POWDER, ACID
	db 36, MURKROW,    PECK, PURSUIT, HAZE, NIGHT_SHADE
	db -1 ; end

	; EXECUTIVEF (2)
	db "EXECUTIVE@", TRAINERTYPE_MOVES
	db 25, ARBOK,      WRAP, LEER, POISON_STING, BITE
	db 25, GLOOM,      ABSORB, SWEET_SCENT, SLEEP_POWDER, ACID
	db 28, MURKROW,    PECK, PURSUIT, HAZE, NO_MOVE
	db -1 ; end

SageGroup:
	; SAGE (1)
	db "CHOW@", TRAINERTYPE_NORMAL
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db -1 ; end

	; SAGE (2)
	db "NICO@", TRAINERTYPE_NORMAL
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db -1 ; end

	; SAGE (3)
	db "JIN@", TRAINERTYPE_NORMAL
	db  6, BELLSPROUT
	db -1 ; end

	; SAGE (4)
	db "TROY@", TRAINERTYPE_NORMAL
	db  7, BELLSPROUT
	db  7, HOOTHOOT
	db -1 ; end

	; SAGE (5)
	db "JEFFREY@", TRAINERTYPE_NORMAL
	db 24, HAUNTER
	db -1 ; end

	; SAGE (6)
	db "PING@", TRAINERTYPE_NORMAL
	db 18, GASTLY
	db 18, GASTLY
	db 18, GASTLY
	db 18, GASTLY
	db 18, GASTLY
	db -1 ; end

	; SAGE (7)
	db "EDMOND@", TRAINERTYPE_NORMAL
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db  3, BELLSPROUT
	db -1 ; end

	; SAGE (8)
	db "NEAL@", TRAINERTYPE_NORMAL
	db  6, BELLSPROUT
	db -1 ; end

	; SAGE (9)
	db "LI@", TRAINERTYPE_NORMAL
	db  7, BELLSPROUT
	db  7, BELLSPROUT
	db 11, HOOTHOOT
	db -1 ; end

MediumGroup:
	; MEDIUM (1)
	db "MARTHA@", TRAINERTYPE_NORMAL
	db 20, GASTLY
	db 22, HAUNTER
	db 22, GASTLY
	db -1 ; end

	; MEDIUM (2)
	db "GRACE@", TRAINERTYPE_NORMAL
	db 22, HAUNTER
	db 22, HAUNTER
	db -1 ; end

	; MEDIUM (3)
	db "BETHANY@", TRAINERTYPE_NORMAL
	db 28, HAUNTER
	db -1 ; end

	; MEDIUM (4)
	db "MARGRET@", TRAINERTYPE_NORMAL
	db 28, HAUNTER
	db -1 ; end

	; MEDIUM (5)
	db "ETHEL@", TRAINERTYPE_NORMAL
	db 28, HAUNTER
	db -1 ; end

	; MEDIUM (6)
	db "REBECCA@", TRAINERTYPE_NORMAL
	db 39, DROWZEE
	db 39, HYPNO
	db -1 ; end

	; MEDIUM (7)
	db "DORIS@", TRAINERTYPE_NORMAL
	db 38, SLOWPOKE
	db 40, SLOWBRO
	db -1 ; end

BoarderGroup:
	; BOARDER (1)
	db "RONALD@", TRAINERTYPE_NORMAL
	db 27, SEEL
	db 28, DEWGONG
	db 27, SEEL
	db -1 ; end

	; BOARDER (2)
	db "BRAD@", TRAINERTYPE_NORMAL
	db 29, SWINUB
	db 29, SWINUB
	db -1 ; end

	; BOARDER (3)
	db "DOUGLAS@", TRAINERTYPE_NORMAL
	db 27, SHELLDER
	db 28, CLOYSTER
	db 27, SHELLDER
	db -1 ; end

PokefanMGroup:
	; POKEFANM (1)
	db "WILLIAM@", TRAINERTYPE_ITEM
	db 15, RAICHU,     BERRY
	db -1 ; end

	; POKEFANM (2)
	db "DEREK@", TRAINERTYPE_ITEM
	db 19, PIKACHU,    BERRY
	db -1 ; end

	; POKEFANM (3)
	db "ROBERT@", TRAINERTYPE_ITEM
	db 37, QUAGSIRE,   BERRY
	db -1 ; end

	; POKEFANM (4)
	db "JOSHUA@", TRAINERTYPE_ITEM
	db 25, PIKACHU,    BERRY
	db 25, PIKACHU,    BERRY
	db 25, PIKACHU,    BERRY
	db 25, PIKACHU,    BERRY
	db 25, PIKACHU,    BERRY
	db 25, PIKACHU,    BERRY
	db -1 ; end

	; POKEFANM (5)
	db "CARTER@", TRAINERTYPE_ITEM
	db 32, BULBASAUR,  BERRY
	db 32, CHARMANDER, BERRY
	db 32, SQUIRTLE,   BERRY
	db -1 ; end

	; POKEFANM (6)
	db "TREVOR@", TRAINERTYPE_ITEM
	db 37, PSYDUCK,    BERRY
	db -1 ; end

	; POKEFANM (7)
	db "BRANDON@", TRAINERTYPE_ITEM
	db 14, SNUBBULL,   BERRY
	db -1 ; end

	; POKEFANM (8)
	db "JEREMY@", TRAINERTYPE_ITEM
	db 31, MEOWTH,     BERRY
	db 31, MEOWTH,     BERRY
	db 31, MEOWTH,     BERRY
	db -1 ; end

	; POKEFANM (9)
	db "COLIN@", TRAINERTYPE_ITEM
	db 36, DELIBIRD,   BERRY
	db -1 ; end

	; POKEFANM (10)
	db "DEREK@", TRAINERTYPE_ITEM
	db 21, PIKACHU,    BERRY
	db -1 ; end

	; POKEFANM (11)
	db "DEREK@", TRAINERTYPE_ITEM
	db 40, PIKACHU,    BERRY
	db -1 ; end

	; POKEFANM (12)
	db "ALEX@", TRAINERTYPE_ITEM
	db 32, NIDOKING,   BERRY
	db 32, SLOWKING,   BERRY
	db 32, SEAKING,    BERRY
	db -1 ; end

KimonoGirlGroup:
	; KIMONO_GIRL (1)
	db "KYOKO@", TRAINERTYPE_NORMAL
	db 22, SKIPLOOM
	db 22, VULPIX
	db 20, SKIPLOOM
	db -1 ; end

	; KIMONO_GIRL (2)
	db "NAOKO@", TRAINERTYPE_NORMAL
	db 19, FLAREON
	db -1 ; end

	; KIMONO_GIRL (3)
	db "SAYO@", TRAINERTYPE_NORMAL
	db 19, ESPEON
	db -1 ; end

	; KIMONO_GIRL (4)
	db "ZUKI@", TRAINERTYPE_NORMAL
	db 19, UMBREON
	db -1 ; end

	; KIMONO_GIRL (5)
	db "KUNI@", TRAINERTYPE_NORMAL
	db 19, VAPOREON
	db -1 ; end

	; KIMONO_GIRL (6)
	db "MIKI@", TRAINERTYPE_NORMAL
	db 19, JOLTEON
	db -1 ; end

TwinsGroup:
	; TWINS (1)
	db "AMY & MAY@", TRAINERTYPE_NORMAL
	db 11, SPINARAK
	db 11, LEDYBA
	db -1 ; end

	; TWINS (2)
	db "ANN & ANNE@", TRAINERTYPE_MOVES
	db 18, CLEFAIRY,   GROWL, ENCORE, DOUBLESLAP, METRONOME
	db 18, JIGGLYPUFF, SING, DEFENSE_CURL, POUND, DISABLE
	db -1 ; end

	; TWINS (3)
	db "ANN & ANNE@", TRAINERTYPE_MOVES
	db 18, JIGGLYPUFF, SING, DEFENSE_CURL, POUND, DISABLE
	db 18, CLEFAIRY,   GROWL, ENCORE, DOUBLESLAP, METRONOME
	db -1 ; end

	; TWINS (4)
	db "AMY & MAY@", TRAINERTYPE_NORMAL
	db 11, LEDYBA
	db 11, SPINARAK
	db -1 ; end

	; TWINS (5)
	db "JO & ZOE@", TRAINERTYPE_NORMAL
	db 39, VICTREEBEL
	db 39, VILEPLUME
	db -1 ; end

	; TWINS (6)
	db "JO & ZOE@", TRAINERTYPE_NORMAL
	db 39, VILEPLUME
	db 39, VICTREEBEL
	db -1 ; end

	; TWINS (7)
	db "MEG & PEG@", TRAINERTYPE_NORMAL
	db 34, TEDDIURSA
	db 34, PHANPY
	db -1 ; end

	; TWINS (8)
	db "MEG & PEG@", TRAINERTYPE_NORMAL
	db 34, PHANPY
	db 34, TEDDIURSA
	db -1 ; end

PokefanFGroup:
	; POKEFANF (1)
	db "BEVERLY@", TRAINERTYPE_ITEM
	db 15, SNUBBULL,   BERRY
	db -1 ; end

	; POKEFANF (2)
	db "RUTH@", TRAINERTYPE_ITEM
	db 19, PIKACHU,    BERRY
	db -1 ; end

	; POKEFANF (3)
	db "BEVERLY@", TRAINERTYPE_ITEM
	db 20, SNUBBULL,   BERRY
	db -1 ; end

	; POKEFANF (4)
	db "BEVERLY@", TRAINERTYPE_ITEM
	db 33, GRANBULL,   BERRY
	db -1 ; end

	; POKEFANF (5)
	db "GEORGIA@", TRAINERTYPE_ITEM
	db 25, SENTRET,    BERRY
	db 25, SENTRET,    BERRY
	db 25, SENTRET,    BERRY
	db 31, FURRET,     BERRY
	db 25, SENTRET,    BERRY
	db -1 ; end

RedGroup:
	; RED (1)
	db "RED@", TRAINERTYPE_MOVES
	db 91, PIKACHU,    CHARM, QUICK_ATTACK, THUNDERBOLT, THUNDER
	db 82, ESPEON,     MUD_SLAP, REFLECT, SWIFT, PSYCHIC_M
	db 84, SNORLAX,    AMNESIA, SNORE, REST, BODY_SLAM
	db 86, VENUSAUR,   SUNNY_DAY, GIGA_DRAIN, SYNTHESIS, SOLARBEAM
	db 86, CHARIZARD,  FLAMETHROWER, WING_ATTACK, SLASH, FIRE_SPIN
	db 86, BLASTOISE,  RAIN_DANCE, SURF, BLIZZARD, WHIRLPOOL
	db -1 ; end

BlueGroup:
	; BLUE (1)
	db "BLUE@", TRAINERTYPE_MOVES
	db 63, PIDGEOT,    QUICK_ATTACK, WHIRLWIND, WING_ATTACK, MIRROR_MOVE
	db 60, ALAKAZAM,   DISABLE, RECOVER, PSYCHIC_M, REFLECT
	db 63, RHYDON,     FURY_ATTACK, SANDSTORM, ROCK_SLIDE, EARTHQUAKE
	db 65, GYARADOS,   TWISTER, HYDRO_PUMP, RAIN_DANCE, HYPER_BEAM
	db 65, EXEGGUTOR,  SUNNY_DAY, LEECH_SEED, EGG_BOMB, SOLARBEAM
	db 65, ARCANINE,   ROAR, SWIFT, FLAMETHROWER, EXTREMESPEED
	db -1 ; end

OfficerGroup:
	; OFFICER (1)
	db "KEITH@", TRAINERTYPE_NORMAL
	db 19, GROWLITHE
	db -1 ; end

	; OFFICER (2)
	db "DIRK@", TRAINERTYPE_NORMAL
	db 15, GROWLITHE
	db 15, GROWLITHE
	db -1 ; end

GruntFGroup:
	; GRUNTF (1)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db  10, ZUBAT
	db 12, EKANS
	db -1 ; end

	; GRUNTF (2)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 29, ARBOK
	db -1 ; end

	; GRUNTF (3)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 28, GLOOM
	db 28, GLOOM
	db -1 ; end

	; GRUNTF (4)
	db "GRUNT@", TRAINERTYPE_NORMAL
	db 23, EKANS
	db 25, ODDISH
	db 23, EKANS
	db 27, GLOOM
	db -1 ; end

	; GRUNTF (5)
	db "GRUNT@", TRAINERTYPE_MOVES
	db 20, EKANS,      WRAP, LEER, POISON_STING, BITE
	db 20, GLOOM,      ABSORB, SWEET_SCENT, STUN_SPORE, SLEEP_POWDER
	db -1 ; end
